#!/usr/bin/env python3
"""Render the authored YAML into a browsable Markdown book under _book/.

YAML is the source of truth and the only thing a compiler will read. This produces the readable
side: the 23 object sections as tables, the executable / blocked split on inference patterns,
the five knowledge-artifact kinds, terminology, and an index that shows at a glance how much of
each brain is authored versus stubbed.

_book/ is GENERATED. Editing it is editing something that will be overwritten.

    python "Domain Expertise/_tools/render.py"
"""
from __future__ import annotations

import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import ROOT, domains, load_set, patterns_of, walk  # noqa: E402

BANNER = "<!-- GENERATED by _tools/render.py — edit the YAML, not this file. -->\n"


def h(level, text):
    return f"\n{'#' * level} {text}\n"


def bullets(items, fmt=str):
    return "\n".join(f"- {fmt(i)}" for i in items) + "\n" if items else "_none_\n"


def cell(v):
    if isinstance(v, list):
        return ", ".join(f"`{x}`" for x in v)
    return str(v).replace("|", "\\|").replace("\n", " ") if v is not None else ""


def table(headers, rows):
    if not rows:
        return "_none_\n"
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(cell(c) for c in r) + " |")
    return "\n".join(out) + "\n"


def cond(c):
    if "fn" in c and "path" in c:
        return f"`{c['fn']}({c['path']}) {c['op']} {c['value']}`"
    if "fn" in c:
        return f"`{c['fn']} {c['op']} {c['value']}`"
    for k in ("exists", "absent", "has_obs", "no_obs", "neighbor_has_obs", "neighbor_no_obs"):
        if k in c:
            return f"`{k}: {c[k]}`"
    if "neighbor_fact" in c:
        return f"`neighbor({c['neighbor_fact']}) {c['op']} {c['value']}`"
    if "path" in c:
        return f"`{c['path']} {c['op']} {c['value']}`"
    return f"`{c}`"


def conds(lst):
    return " AND ".join(cond(c) for c in (lst or [])) or "—"


def head(d, extra=""):
    i = d["identity"]
    bits = [f"`{i['id']}`", f"v{i.get('version', '?')}", f"**{i.get('status', '?')}**"]
    if i.get("scope"):
        bits.append(f"scope **{i['scope']}**")
    return [BANNER, f"# {i['name']}", "", " · ".join(bits) + extra, ""]


# ── objects ──────────────────────────────────────────────────────────────────────────────
def render_object(d):
    i, p = d["identity"], d.get("purpose") or {}
    md = head(d)
    md.append(f"> {p.get('statement', '').strip()}\n")
    if p.get("discriminator"):
        md.append(f"\n**The discriminator.** {p['discriminator'].strip()}\n")
    if i.get("aliases"):
        md.append(f"\nAlso called: {', '.join(f'`{a}`' for a in i['aliases'])}\n")
    for key, title in [("answers", "Questions this object answers"),
                       ("not", "What it is NOT responsible for")]:
        if p.get(key):
            md.append(h(3, title))
            md.append(bullets(p[key]))

    attrs = d.get("attributes") or []
    md.append(h(2, f"Attributes ({len(attrs)})"))
    md.append(table(["Attribute", "Type", "Data", "Req", "Purpose", "Source / contains"],
                    [(f"`{a['name']}`", a.get("type", ""), a.get("data_type", ""),
                      "yes" if a.get("required") else "", a.get("purpose", ""),
                      a.get("contains") or a.get("source_paths") or a.get("derived_from")
                      or a.get("ref") or "")
                     for a in attrs]))

    md.append(h(2, "Relationships"))
    md.append(table(["Verb", "Target", "Card.", "Weight", "Conf.", "When", "Notes"],
                    [(r.get("type") or r.get("verb", ""), f"`{r.get('target')}`",
                      r.get("cardinality", ""),
                      f"{r['weight_bp']} bp" if r.get("weight_bp") is not None else "",
                      f"{r['confidence_bp']} bp" if r.get("confidence_bp") is not None else "",
                      conds(r.get("conditions")), r.get("description", ""))
                     for r in d.get("relationships") or []]))

    if d.get("states"):
        s = d["states"]
        md.append(h(2, "States"))
        md.append(f"Initial `{s.get('initial', '?')}`"
                  + (f" · terminal {', '.join(f'`{t}`' for t in s['terminal'])}"
                     if s.get("terminal") else "") + "\n")
        md.append(table(["State", "Means", "Entered when", "Implies"],
                        [(f"`{v['name']}`", v.get("description", ""),
                          conds(v.get("entered_when")), v.get("implies", ""))
                         for v in s.get("values", [])]))

    ex, ns = [], []
    for k, pat in patterns_of(d):
        (ex if pat.get("status") == "executable" else ns).append((k, pat))
    md.append(h(2, f"Inference patterns — {len(ex)} executable, {len(ns)} blocked"))
    md.append(h(3, "Executable against the pipeline today"))
    md.append(table(["Pattern", "Kind", "Reads", "Yields", "Statement", "False positive"],
                    [(f"`{p['id']}`", k, conds(p.get("when")),
                      f"{p['yields']['confidence_bp']} bp"
                      + (f" → `{p['yields']['attribute']}`" if p["yields"].get("attribute") else ""),
                      p["statement"], p.get("false_positive", "")) for k, p in ex]))
    md.append(h(3, "Blocked — needs a signal the pipeline does not emit"))
    md.append(table(["Pattern", "Kind", "Needs", "Would yield", "Statement"],
                    [(f"`{p['id']}`", k,
                      ", ".join(f"`{r['name']}` ({r['kind']})"
                                for r in p.get("requires_signals", [])),
                      f"{p['yields']['confidence_bp']} bp", p["statement"]) for k, p in ns]))

    if d.get("decision_factors"):
        md.append(h(2, "Decision factors"))
        md.append(table(["Factor", "Weight", "Direction", "Reads"],
                        [(f["name"], f"{f.get('weight_bp', 0)} bp", f.get("direction", ""),
                          f.get("reads")) for f in d["decision_factors"]]))

    for key, title, fmt in [
        ("preconditions", "Preconditions",
         lambda x: f"**`{x['id']}`** {x['statement']}"
                   + (f" _(unmet → {x['if_unmet']})_" if x.get("if_unmet") else "")),
        ("constraints", "Constraints",
         lambda x: f"**`{x['id']}`** {x['statement']}"
                   + ("" if x.get("hard", True) else " _(soft)_")),
        ("business_rules", "Business rules",
         lambda x: f"**`{x['id']}`** {x['statement']}"
                   + (f" — _{x['why']}_" if x.get("why") else "")),
        ("exceptions", "Exceptions — where the rules above are legitimately wrong",
         lambda x: f"**{x['statement']}**"
                   + (f" — {x['why']}" if x.get("why") else "")
                   + (f" _(overrides {', '.join(x['overrides'])})_" if x.get("overrides") else "")),
        ("best_practices", "Best practices",
         lambda x: f"**{x['statement']}**" + (f" — {x['why']}" if x.get("why") else "")),
        ("anti_patterns", "Anti-patterns",
         lambda x: f"**{x['statement']}**"
                   + (f" — tempting because {x['why_it_happens']}" if x.get("why_it_happens") else "")
                   + (f" Instead: {x['instead']}" if x.get("instead") else "")),
        ("dependencies", "Dependencies",
         lambda x: f"`{x['target']}` — {x['kind']}"
                   + (f" ({x['strength']})" if x.get("strength") else "")),
        ("inputs", "Inputs", lambda x: f"**{x['source']}** — {x.get('signal', '')}"),
        ("outputs", "Outputs",
         lambda x: f"**`{x['name']}`** {x.get('description', '')} "
                   f"→ {', '.join(x.get('consumed_by', []))}"),
        ("events", "Events",
         lambda x: f"**`{x['id']}`** {x['name']}"
                   + (f" — invalidates {', '.join(x['invalidates'])}" if x.get("invalidates") else "")),
        ("actions", "Actions",
         lambda x: f"**{x['name']}** ({x.get('actor', '?')}) — {x.get('effect', '')}"),
        ("evidence", "Evidence",
         lambda x: f"**{x['source']}** · {x.get('strength_bp', 0)} bp — {x.get('description', '')}"),
        ("metrics", "Metrics",
         lambda x: f"**{x['name']}** ({x.get('unit', '')}) — {x.get('description', '')}"),
        ("references", "References",
         lambda x: f"**{x['title']}**" + (f" · {x['kind']}" if x.get("kind") else "")
                   + (f" · {x['author']}" if x.get("author") else "")),
    ]:
        if d.get(key):
            md.append(h(2, title))
            md.append(bullets(d[key], fmt))

    if d.get("examples"):
        md.append(h(2, "Examples"))
        md.append(bullets(d["examples"],
                          lambda e: e if isinstance(e, str)
                          else f"**{e['label']}**"
                               + (f" _({e['kind']})_" if e.get("kind") else "")
                               + (f" — {e['note']}" if e.get("note") else "")))
    return "\n".join(md) + meta_block(d)


def meta_block(d):
    m = d.get("metadata") or {}
    out = [h(2, "Metadata"),
           f"owner **{m.get('owner', '?')}** · updated {m.get('last_updated', '?')} · "
           f"review **{m.get('review_status', '?')}** · confidence "
           f"**{m.get('confidence', '?')}**"
           + (f" · completeness **{m['completeness']}**" if m.get("completeness") else "") + "\n"]
    if m.get("notes"):
        out.append(f"\n> {m['notes'].strip()}\n")
    return "\n".join(out)


# ── knowledge artifacts ──────────────────────────────────────────────────────────────────
def render_artifact(d):
    i, p = d["identity"], d.get("purpose") or {}
    md = head(d, f" · kind **{i.get('kind', '?')}**")
    md.append(f"> {p.get('statement', '').strip()}\n")

    if d.get("heuristic"):
        hh = d["heuristic"]
        md.append(h(2, "The heuristic"))
        md.append(f"**{hh['statement']}**\n")
        md.append(f"\n_Why:_ {hh.get('why', '')}\n")
        if hh.get("breaks_down_when"):
            md.append(f"\n_Breaks down when:_ {hh['breaks_down_when']}\n")
        if hh.get("confidence_bp") is not None:
            md.append(f"\nConfidence {hh['confidence_bp']} bp\n")
        if hh.get("contradicts"):
            md.append(f"\nIn tension with: {', '.join(f'`{c}`' for c in hh['contradicts'])}\n")

    if d.get("rule"):
        r = d["rule"]
        md.append(h(2, "The rule"))
        md.append(f"**{r['statement']}**\n")
        md.append(f"\nSpans {', '.join(f'`{s}`' for s in r.get('spans', []))} · "
                  f"severity **{r.get('severity', '?')}** · "
                  f"enforced by `{r.get('enforced_by', 'unspecified')}`\n")
        if r.get("when"):
            md.append(f"\nWhen: {conds(r['when'])}\n")
        if r.get("why"):
            md.append(f"\n_Why:_ {r['why']}\n")

    if d.get("dimensions"):
        md.append(h(2, "Dimensions"))
        md.append(table(["Dimension", "Asks", "Weak signal", "Strong signal", "Objects"],
                        [(x["name"], x.get("asks", ""), x.get("weak_signal", ""),
                          x.get("strong_signal", ""), x.get("objects"))
                         for x in d["dimensions"]]))

    if d.get("criteria"):
        md.append(h(2, "Criteria"))
        md.append(table(["Criterion", "Weight", "Disqualifying", "Reads", "Notes"],
                        [(x["name"],
                          f"{x['weight_bp']} bp" if x.get("weight_bp") is not None else "",
                          "yes" if x.get("disqualifying") else "", x.get("reads"),
                          x.get("description", "")) for x in d["criteria"]]))

    if d.get("steps"):
        md.append(h(2, "Steps"))
        md.append(table(["#", "Step", "Actor", "Produces", "Done when"],
                        [(x["order"], x["name"], x.get("actor", ""), x.get("produces", ""),
                          x.get("done_when", "")) for x in sorted(d["steps"],
                                                                  key=lambda s: s["order"])]))

    if d.get("when_to_use"):
        w = d["when_to_use"]
        md.append(h(2, "When to use"))
        if w.get("situations"):
            md.append(bullets(w["situations"], lambda s: f"`{s}`"))
        if w.get("conditions"):
            md.append(f"\nConditions: {conds(w['conditions'])}\n")
        if w.get("do_not_use_when"):
            md.append(h(3, "Do not use when"))
            md.append(bullets(w["do_not_use_when"]))

    for key, title in [("how_to_apply", "How to apply"), ("outcomes", "Outcomes"),
                       ("failure_modes", "Failure modes"), ("limits", "Limits")]:
        if d.get(key):
            md.append(h(2, title))
            md.append(bullets(d[key]))

    if d.get("variants"):
        md.append(h(2, "Variants by model or offering"))
        md.append(table(["Applies to", "Change", "Why"],
                        [(f"`{v['applies_to']}`", v["change"], v.get("why", ""))
                         for v in d["variants"]]))
    if d.get("objects_used"):
        md.append(h(2, "Objects used"))
        md.append(bullets(d["objects_used"], lambda x: f"`{x}`"))
    if d.get("references"):
        md.append(h(2, "References"))
        md.append(bullets(d["references"],
                          lambda x: f"**{x['title']}**"
                                    + (f" · {x['kind']}" if x.get("kind") else "")
                                    + (f" · {x['author']}" if x.get("author") else "")))
    return "\n".join(md) + meta_block(d)


def render_terminology(d):
    md = [BANNER, f"# Terminology — {d['area'].replace('_', ' ').title()}", "",
          f"`{d['domain']}` · {len(d.get('terms', []))} terms", ""]
    md.append(table(["Term", "Definition", "Also called", "Register", "Object"],
                    [(f"**{t['term']}**", t["definition"], t.get("aliases"),
                      t.get("register", ""), f"`{t['object_ref']}`" if t.get("object_ref") else "")
                     for t in d.get("terms", [])]))
    confus = [(t["term"], c["term"], c["difference"])
              for t in d.get("terms", []) for c in (t.get("not_to_be_confused_with") or [])]
    if confus:
        md.append(h(2, "Routinely confused"))
        md.append("The pairs where two teams mean different things by the same word.\n")
        md.append(table(["This", "Not this", "The difference"], confus))
    return "\n".join(md) + meta_block({"metadata": d.get("metadata", {})})


def know(item):
    if isinstance(item, str):
        return item
    out = f"**{item['statement']}**"
    if item.get("why"):
        out += f" — {item['why']}"
    return out


def render_capability(d, objs=None, kn=None, sits=None):
    i = d["identity"]
    md = head(d, " · **STUB**" if i.get("stub") else "")
    md.append(f"**{d['question']}**\n")
    md.append(f"\n> {d['description'].strip()}\n")
    if i.get("parent_capability"):
        md.append(f"\nA channel or sub-discipline of `{i['parent_capability']}`.\n")

    if objs:
        md.append(h(2, "Objects loaded"))
        for bucket, label in [("core", "Core — shared"), ("scoped", "Scoped — this capability only")]:
            b = objs.get(bucket) or {}
            if not (b.get("required") or b.get("optional")):
                continue
            md.append(f"\n**{label} · required**\n")
            md.append(bullets(b.get("required") or [], lambda x: f"`{x}`"))
            if b.get("optional"):
                md.append(f"\n**{label} · optional** — absence lowers confidence, does not block\n")
                md.append(bullets(b["optional"], lambda x: f"`{x}`"))
        if objs.get("notes"):
            md.append(f"\n> {objs['notes'].strip()}\n")

    if kn:
        md.append(h(2, "Expertise applied"))
        if kn.get("primary_framework"):
            md.append(f"Primary framework: `{kn['primary_framework']}`\n")
        for key, title in [("playbooks", "Playbooks"), ("heuristics", "Heuristics"),
                           ("mental_models", "Mental models"), ("rules", "Rules"),
                           ("decision_frameworks", "Decision frameworks")]:
            block = kn.get(key) or {}
            refs = (block.get("core") or []) + (block.get("scoped") or [])
            if refs:
                md.append(h(3, title))
                md.append(bullets(refs, lambda x: f"`{x}`"))

    for key, title in [("outcomes", "Outcomes"), ("failure_modes", "Failure modes")]:
        if d.get(key):
            md.append(h(2, title))
            md.append(bullets(d[key], know))
    if sits:
        md.append(h(2, "Situations owned"))
        md.append(bullets(sits, lambda s: f"[{s[0]}](situations/{s[1]}) — binds "
                                          f"{', '.join(f'`{t}`' for t in s[2])}"))
    if d.get("kpis"):
        md.append(h(2, "KPIs"))
        md.append(table(["KPI", "Unit", "Direction", "Notes"],
                        [(k["name"], k.get("unit", ""), k.get("direction", ""),
                          k.get("description", "")) for k in d["kpis"]]))
    if d.get("handoffs"):
        ho = d["handoffs"]
        md.append(h(2, "Handoffs"))
        for key, label in [("upstream", "Upstream"), ("downstream", "Downstream"),
                           ("parallel", "Parallel")]:
            md.append(f"**{label}:** {', '.join(f'`{c}`' for c in ho.get(key, [])) or '—'}\n\n")
    return "\n".join(md) + meta_block(d)


def render_situation(d):
    i, m = d["identity"], d["matches"]
    md = head(d)
    md.append(f"Owned by `{i.get('owner_capability', '?')}`\n")
    md.append(f"\n> {d['description'].strip()}\n")
    md.append(h(2, "Layer 2 binding"))
    md.append("The join that makes this situation reachable. An unbound situation never "
              "compiles, and nothing errors when it doesn't.\n")
    md.append(bullets(m["l2_situation_types"], lambda t: f"`{t}`"))
    if m.get("when"):
        md.append(f"\nNarrowed by {conds(m['when'])}\n")
    if m.get("scope"):
        md.append(f"\nScope `{m['scope']}`\n")
    o = d["objects"]
    md.append(h(2, "Object load-set"))
    md.append(bullets(o["load"], lambda x: f"`{x}`"))
    for key, title in [("optional", "Optional"), ("never_load", "Never load")]:
        if o.get(key):
            md.append(h(3, title))
            md.append(bullets(o[key], lambda x: f"`{x}`"))
    if d.get("also_serves"):
        md.append(h(2, "Also serves"))
        md.append(bullets(d["also_serves"], lambda x: f"`{x}`"))
    for key, title in [("signals_of_progress", "Signals of progress"),
                       ("signals_of_decay", "Signals of decay")]:
        if d.get(key):
            md.append(h(2, title))
            md.append(bullets(d[key], lambda x: f"`{x}`"))
    return "\n".join(md) + meta_block(d)


def render_branch(d):
    i = d["identity"]
    md = [BANNER, f"# {i['name']}", "",
          f"`{i['id']}` · {i['kind']} · parent `{i.get('parent') or '—'}`", "",
          f"> {d['description'].strip()}", ""]
    if d.get("characteristics"):
        md.append(h(2, "Characteristics"))
        md.append(table(["", ""], list(d["characteristics"].items())))
    c = d.get("capabilities") or {}
    for key, title in [("activates", "Activates"), ("deactivates", "Deactivates"),
                       ("emphasises", "Emphasises")]:
        if c.get(key):
            md.append(h(2, title))
            md.append(bullets(c[key], lambda x: f"`{x}`"))
    for e in (d.get("objects") or {}).get("extends") or []:
        md.append(h(2, f"Extends `{e['object']}`"))
        if e.get("require_properties"):
            md.append(f"Requires {', '.join(f'`{p}`' for p in e['require_properties'])}\n")
        if e.get("note"):
            md.append(f"\n> {e['note'].strip()}\n")
    return "\n".join(md) + meta_block(d)


RENDER = {"object": render_object, "artifact": render_artifact,
          "terminology": render_terminology, "capability": render_capability,
          "situation": render_situation, "model": render_branch, "offering": render_branch}


def main() -> int:
    book = ROOT / "_book"
    if book.exists():
        shutil.rmtree(book)

    for droot in domains():
        files = list(walk(droot))
        capobjs = {d["capability"]: d for k, _, d in files
                   if k == "capability_objects" and d.get("capability")}
        capknow = {d["capability"]: d for k, _, d in files
                   if k == "capability_knowledge" and d.get("capability")}
        sits_by_owner: dict = {}
        for k, p, d in files:
            if k != "situation" or not d.get("identity"):
                continue
            sits_by_owner.setdefault(d["identity"].get("owner_capability"), []).append(
                (d["identity"]["name"], p.with_suffix(".md").name,
                 (d.get("matches") or {}).get("l2_situation_types") or []))

        counts: dict = {}
        entries: dict = {k: [] for k in RENDER}
        for kind, path, d in files:
            if kind not in RENDER:
                continue
            rel = path.relative_to(droot).with_suffix(".md")
            out = book / droot.name / rel
            out.parent.mkdir(parents=True, exist_ok=True)
            if kind == "capability":
                cid = d["identity"]["id"]
                body = render_capability(d, capobjs.get(cid), capknow.get(cid),
                                         sorted(sits_by_owner.get(cid, [])))
            else:
                body = RENDER[kind](d)
            out.write_text(body)
            counts[kind] = counts.get(kind, 0) + 1
            ident = d.get("identity") or {}
            entries[kind].append((ident.get("name") or d.get("area", path.stem),
                                  rel.as_posix(), ident.get("stub", False),
                                  ident.get("scope"), ident.get("kind")))

        dom = next(d for k, _, d in files if k == "domain")
        objs = entries["object"]
        arts = entries["artifact"]
        idx = [BANNER, f"# {dom['identity']['name']} — Expert Brain", "",
               f"**{dom['question']}**", "", f"> {dom['description'].strip()}", "",
               f"`{len(entries['capability'])}` capabilities · `{len(objs)}` objects · "
               f"`{len(arts)}` knowledge artifacts · "
               f"`{len(entries['situation'])}` situations", ""]

        def section(title, rows, note=""):
            idx.append(h(2, f"{title} ({len(rows)})"))
            if note:
                idx.append(note + "\n")
            idx.append("\n".join(f"- [{n}]({p}){' · _stub_' if s else ''}"
                                 for n, p, s, _sc, _k in sorted(rows)) + "\n")

        section("Core objects", [e for e in objs if e[3] == "core"],
                "Shared — loaded by more than one capability.")
        section("Scoped objects", [e for e in objs if e[3] != "core"],
                "Loaded by exactly one capability.")
        for kind, label in [("mental_model", "Mental models"), ("decision_framework",
                            "Decision frameworks"), ("playbook", "Playbooks"),
                            ("heuristic", "Heuristics"), ("rule", "Rules")]:
            rows = [e for e in arts if e[4] == kind]
            if rows:
                section(label, rows)
        for kind, label in [("capability", "Capabilities"), ("situation", "Situations"),
                            ("terminology", "Terminology"), ("model", "Sales models"),
                            ("offering", "Offerings")]:
            if entries[kind]:
                section(label, entries[kind])

        (book / droot.name / "index.md").write_text("\n".join(idx))
        print(f"{droot.name}: " + " · ".join(f"{v} {k}" for k, v in sorted(counts.items())))
    print("\n_book/ written. Generated — edit the YAML, not the Markdown.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
