-- The payload projection check must stop asserting a field the payload no longer carries.
--
-- `expertise_packages.payload` is the canonical form of `ExpertisePackage.to_semantic_dict()`,
-- and `trace_id` was removed from that method because it is observation metadata, not content:
-- `domain_shadow` mints a fresh `new_id("trace")` per situation per sweep, so hashing it made
-- every compile content-address to a new id, the publisher's `on conflict do nothing` never
-- fired, and unchanged knowledge was rewritten at ~238 kB a situation until this table reached
-- 995 MB — 67% of the database — and the project crossed its disk quota into read-only.
--
-- Left alone, `payload->>'trace_id' = trace_id` does not fail: `payload->>'trace_id'` is NULL,
-- NULL = <text> is NULL, and a CHECK passes on NULL. So the constraint would keep its name and
-- quietly stop checking anything — worse than dropping the clause, because the next person to
-- read it would believe the projection is still verified end to end. The remaining columns are
-- still projected, and `trace_id` remains a NOT NULL column: it is stored and still ties a
-- package to the sweep that observed it. It just is not in the payload, so it is not asserted
-- against the payload.
alter table expertise_packages drop constraint if exists expertise_payload_projection;

-- THE ROWS MUST BE DELETED, NOT REWRITTEN — the table refuses updates by design.
--
-- Two earlier attempts failed here and both diagnoses were wrong. The rows were not individually
-- invalid (every other clause measured zero violations on all 304), and it was not a race with
-- the still-running old pod. Reproduced on a scratch Postgres with one prod-shaped row, the real
-- error is unambiguous:
--
--   psycopg.errors.RaiseException: ExpertisePackage rows are immutable
--   CONTEXT: PL/pgSQL function reject_expertise_package_update()
--
-- A published package is immutable by contract, and an UPDATE that strips a payload key is still
-- an update. The trigger is right and the migration was wrong to try.
--
-- DELETE is not a workaround, it is the correct operation. `trace_id` was part of the content
-- address these rows were minted under, so under the new addressing they are not the same
-- packages under a different shape — they are packages whose id no longer describes their
-- content. They are derived data, regenerated by the next sweep, and the publisher's
-- `on conflict do nothing` will mint them fresh with a correct id.
--
-- The lock stays, and still earns its place: the deploy is zero-downtime, the previous pod keeps
-- sweeping, and `PostgresExpertisePublisher` writes a new old-format row on every situation of
-- every sweep — this table went 76 -> 304 rows between a manual truncate and a failed deploy. A
-- row committed between the delete and the constraint's own lock would fail the validation and
-- roll the whole migration back. `ADD CONSTRAINT` acquires this lock regardless; taking it first
-- only moves it earlier.
lock table expertise_packages in access exclusive mode;

delete from expertise_packages where payload ? 'trace_id';

alter table expertise_packages add constraint expertise_payload_projection check (
    payload->>'org_id' = org_id
    and payload->>'id' = expertise_id
    and payload->>'schema_version' = schema_version
    and payload->>'situation_id' = situation_id
    and payload->>'brain_snapshot_id' = brain_snapshot_id
    and payload->'visibility' = visibility
    and payload->'trace_id' is null);
