#!/usr/bin/env node
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

const API_KEY = process.env.GENIOS_API_KEY;
const BASE_URL = (process.env.GENIOS_BASE_URL ?? "https://squid-app-2zuqf.ondigitalocean.app").replace(/\/$/, "");
const AGENT_ID = process.env.GENIOS_AGENT_ID ?? "claude-mcp";

if (!API_KEY) {
  console.error("[genios-mcp] GENIOS_API_KEY not set — tools will fail.");
}

function headers() {
  return {
    Authorization: `Bearer ${API_KEY}`,
    "Content-Type": "application/json",
  };
}

async function get(path: string, params?: Record<string, string | number | boolean>) {
  const url = new URL(`${BASE_URL}${path}`);
  if (params) {
    for (const [k, v] of Object.entries(params)) url.searchParams.set(k, String(v));
  }
  const res = await fetch(url.toString(), { headers: headers() });
  if (!res.ok) return { error: `HTTP ${res.status}`, body: (await res.text()).slice(0, 500) };
  return res.json();
}

async function post(path: string, payload: Record<string, unknown>) {
  const res = await fetch(`${BASE_URL}${path}`, {
    method: "POST",
    headers: headers(),
    body: JSON.stringify(payload),
  });
  if (!res.ok) return { error: `HTTP ${res.status}`, body: (await res.text()).slice(0, 500) };
  return res.json();
}

const server = new Server(
  { name: "genios", version: "1.0.0" },
  {
    capabilities: { tools: {} },
    instructions:
      "You have access to genios_* tools that are ALWAYS available — call them directly, no pre-loading needed. " +
      "NEVER fabricate, guess, or infer relationship data. If a tool call fails or returns an error, respond with exactly: " +
      "'GeniOS data unavailable. Please try again.' and stop. " +
      "When the user asks for priorities, alerts, or relationship status: call genios_list_insights first, then genios_org_info. " +
      "Always cite the tool result — never present data you did not receive from a tool call.",
  }
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "genios_search_contacts",
      description:
        "Search or list contacts in the user's Genios brain. Use this FIRST when the user mentions someone by partial name — resolve to a canonical email, THEN call genios_get_context.",
      inputSchema: {
        type: "object",
        properties: {
          q: { type: "string", description: "Partial name, email, or company." },
          stage: { type: "string", description: "ACTIVE | WARM | COLD | DORMANT | NEEDS_ATTENTION | AT_RISK" },
          needs_attention: { type: "boolean" },
          recent_days: { type: "number" },
          silent_days: { type: "number" },
          overdue: { type: "boolean" },
          limit: { type: "number", default: 20 },
        },
      },
    },
    {
      name: "genios_get_context",
      description:
        "Retrieve relationship memory for a person or company. Call this BEFORE drafting emails or planning outreach. Returns relationship_stage, sentiment_trend, open_commitments, and agent guidance. " +
        "IMPORTANT: When the response includes a `related_outbound` field, it lists the user's recent outbound messages on the same topic to OTHER contacts — read those excerpts and reuse the framing instead of asking the user for context that's already there.",
      inputSchema: {
        type: "object",
        properties: {
          entity: { type: "string", description: "Email, full name, or company name." },
          situation: { type: "string", description: "What you're about to do — helps Genios return the most relevant context." },
        },
        required: ["entity"],
      },
    },
    {
      name: "genios_list_segments",
      description: "List all contact segments defined in the user's Genios brain.",
      inputSchema: { type: "object", properties: {} },
    },
    {
      name: "genios_get_segment_members",
      description: "Enumerate contacts in a specific segment.",
      inputSchema: {
        type: "object",
        properties: {
          segment_id: { type: "string" },
          limit: { type: "number", default: 50 },
        },
        required: ["segment_id"],
      },
    },
    {
      name: "genios_org_info",
      description: "Org profile, plan tier, usage stats, and graph totals.",
      inputSchema: { type: "object", properties: {} },
    },
    {
      name: "genios_list_insights",
      description: "List proactive insights generated by GeniOS — anomalies, cooling relationships, overdue commitments.",
      inputSchema: {
        type: "object",
        properties: {
          status: { type: "string", description: "pending | delivered | dismissed" },
          limit: { type: "number", default: 10 },
        },
      },
    },
    {
      name: "genios_log_interaction",
      description: "Write-back: log an action you just took on a contact. Call this AFTER sending an email or any outreach.",
      inputSchema: {
        type: "object",
        properties: {
          entity: { type: "string" },
          summary: { type: "string" },
          direction: { type: "string", default: "outbound" },
          channel: { type: "string", default: "email" },
          sentiment: { type: "number" },
          topics: { type: "array", items: { type: "string" } },
        },
        required: ["entity", "summary"],
      },
    },
    {
      name: "genios_log_outcome",
      description: "Feedback: report whether the context you got was useful.",
      inputSchema: {
        type: "object",
        properties: {
          context_id: { type: "string" },
          outcome: { type: "string", description: "positive | negative | neutral" },
          details: { type: "string" },
        },
        required: ["context_id", "outcome"],
      },
    },
    {
      name: "genios_trigger_scan",
      description: "Trigger a manual proactive scan — runs anomaly detection and generates fresh insights.",
      inputSchema: { type: "object", properties: {} },
    },
    {
      name: "genios_sync_status",
      description: "Check data source sync state (Gmail, Calendar, Slack, etc.)",
      inputSchema: { type: "object", properties: {} },
    },
    {
      name: "genios_search_messages",
      description:
        "Search the user's own recent sent + received messages across the whole network. Use this when drafting outreach to find similar prior messages the user has already written on the same topic — reuse their framing instead of asking them for context. Also for 'what did I say about X last week' or 'who have I been emailing about project Y'. Scoped to caller's org; respects privacy.",
      inputSchema: {
        type: "object",
        properties: {
          q: { type: "string", description: "Keyword/phrase (full-text over subject + body)." },
          direction: { type: "string", description: "outbound | inbound. Omit for both." },
          days: { type: "number", default: 14, description: "Recency window in days (1-365)." },
          limit: { type: "number", default: 10, description: "Max results (1-50)." },
          contact_id: { type: "string", description: "Optional: scope to a single contact UUID." },
        },
      },
    },
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const { name, arguments: args = {} } = req.params;
  let data: unknown;

  if (name === "genios_search_contacts") {
    const params: Record<string, string | number | boolean> = {};
    if (args.q) params.q = String(args.q);
    if (args.stage) params.stage = String(args.stage);
    if (args.needs_attention) params.needs_attention = true;
    if (args.recent_days != null) params.recent_days = Number(args.recent_days);
    if (args.silent_days != null) params.silent_days = Number(args.silent_days);
    if (args.overdue) params.overdue = true;
    if (args.limit) params.limit = Number(args.limit);
    data = await get("/v1/contacts", params);
  } else if (name === "genios_get_context") {
    const payload: Record<string, unknown> = { entity: args.entity, agent_id: AGENT_ID };
    if (args.situation) payload.situation = String(args.situation).slice(0, 500);
    data = await post("/v1/context", payload);
  } else if (name === "genios_list_segments") {
    data = await get("/v1/segments");
  } else if (name === "genios_get_segment_members") {
    data = await get(`/v1/segment/${args.segment_id}/members`, { limit: Number(args.limit ?? 50) });
  } else if (name === "genios_org_info") {
    data = await get("/v1/org");
  } else if (name === "genios_sync_status") {
    data = await get("/v1/sync");
  } else if (name === "genios_list_insights") {
    const params: Record<string, string | number> = {};
    if (args.status) params.status = String(args.status);
    if (args.limit) params.limit = Number(args.limit);
    data = await get("/v1/insights", params);
  } else if (name === "genios_log_interaction") {
    const payload: Record<string, unknown> = {
      entity: args.entity,
      summary: args.summary,
      agent_id: AGENT_ID,
    };
    for (const k of ["direction", "channel", "sentiment", "topics"]) {
      if (args[k] != null) payload[k] = args[k];
    }
    data = await post("/v1/interaction", payload);
  } else if (name === "genios_log_outcome") {
    const payload: Record<string, unknown> = {
      context_id: args.context_id,
      outcome: args.outcome,
      agent_id: AGENT_ID,
    };
    if (args.details) payload.details = args.details;
    data = await post("/v1/outcome", payload);
  } else if (name === "genios_trigger_scan") {
    data = await post("/v1/scan", {});
  } else if (name === "genios_search_messages") {
    const params: Record<string, string | number> = {};
    if (args.q) params.q = String(args.q);
    if (args.direction) params.direction = String(args.direction);
    if (args.days != null) params.days = Number(args.days);
    if (args.limit != null) params.limit = Number(args.limit);
    if (args.contact_id) params.contact_id = String(args.contact_id);
    data = await get("/v1/messages/search", params);
  } else {
    data = { error: `unknown tool: ${name}` };
  }

  return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] };
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
