"""
Phase 6.4: Proactive mode API endpoints.

GET  /v1/insights              — list pending/active insights for the org
POST /v1/insights/:id/dismiss  — dismiss an insight
GET  /v1/webhooks              — list webhook configs
POST /v1/webhooks              — register a webhook endpoint
DELETE /v1/webhooks/:id        — remove a webhook
POST /v1/scan                  — trigger a manual proactive scan (Startup only)
"""
import secrets
import logging
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel
from sqlalchemy import text
from sqlalchemy.orm import Session

from app.api.deps import get_db, verify_api_key

logger = logging.getLogger(__name__)

router = APIRouter()


# ── Insights ─────────────────────────────────────────────────────────────────

@router.get("/v1/insights")
def list_insights(
    status: Optional[str] = Query(None, description="Filter: pending | delivered | dismissed"),
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db),
    org_id: str = Depends(verify_api_key),
):
    """List insights generated by the proactive scanner."""
    where = ["i.org_id = :org_id"]
    params = {"org_id": org_id, "limit": limit}

    if status == "dismissed":
        where.append("i.is_dismissed = TRUE")
    elif status:
        where.append("i.delivery_status = :status")
        params["status"] = status
    else:
        where.append("i.is_dismissed = FALSE")

    rows = db.execute(
        text(f"""
            SELECT i.id, i.insight_type, i.priority, i.category,
                   i.title, i.detail, i.contact_name, i.contact_id,
                   i.memory_view, i.genios_view,
                   i.delivery_status, i.generated_at, i.delivered_at,
                   i.source_type
            FROM insights i
            WHERE {' AND '.join(where)}
            ORDER BY
                CASE i.priority WHEN 'high' THEN 0 WHEN 'medium' THEN 1 ELSE 2 END,
                i.generated_at DESC
            LIMIT :limit
        """),
        params,
    ).fetchall()

    return {
        "insights": [
            {
                "id": str(r.id),
                "type": r.insight_type,
                "priority": r.priority,
                "category": r.category,
                "title": r.title,
                "detail": r.detail,
                "contact_name": r.contact_name,
                "contact_id": str(r.contact_id) if r.contact_id else None,
                "memory_view": r.memory_view,
                "genios_view": r.genios_view,
                "delivery_status": r.delivery_status,
                "source": r.source_type,
                "generated_at": r.generated_at.isoformat() if r.generated_at else None,
                "delivered_at": r.delivered_at.isoformat() if r.delivered_at else None,
            }
            for r in rows
        ],
        "count": len(rows),
    }


@router.post("/v1/insights/{insight_id}/dismiss")
def dismiss_insight(
    insight_id: str,
    db: Session = Depends(get_db),
    org_id: str = Depends(verify_api_key),
):
    result = db.execute(
        text("UPDATE insights SET is_dismissed = TRUE WHERE id = :id AND org_id = :oid RETURNING id"),
        {"id": insight_id, "oid": org_id},
    ).fetchone()
    if not result:
        raise HTTPException(status_code=404, detail="Insight not found")
    db.commit()
    return {"dismissed": True, "id": insight_id}


# ── Webhooks ─────────────────────────────────────────────────────────────────

@router.get("/v1/webhooks")
def list_webhooks(
    db: Session = Depends(get_db),
    org_id: str = Depends(verify_api_key),
):
    rows = db.execute(
        text("""
            SELECT id, url, is_active, events, created_at,
                   last_delivery_at, consecutive_failures
            FROM webhook_config
            WHERE org_id = :oid
            ORDER BY created_at ASC
        """),
        {"oid": org_id},
    ).fetchall()
    return {
        "webhooks": [
            {
                "id": str(r.id),
                "url": r.url,
                "is_active": r.is_active,
                "events": r.events or [],
                "created_at": r.created_at.isoformat() if r.created_at else None,
                "last_delivery_at": r.last_delivery_at.isoformat() if r.last_delivery_at else None,
                "consecutive_failures": r.consecutive_failures or 0,
            }
            for r in rows
        ],
        "count": len(rows),
    }


class CreateWebhookRequest(BaseModel):
    url: str
    events: list[str] = ["insight"]


@router.post("/v1/webhooks", status_code=201)
def create_webhook(
    req: CreateWebhookRequest,
    db: Session = Depends(get_db),
    org_id: str = Depends(verify_api_key),
):
    if not req.url.startswith("https://"):
        raise HTTPException(status_code=400, detail="Webhook URL must use HTTPS")

    # Generate signing secret
    secret = secrets.token_urlsafe(32)

    try:
        result = db.execute(
            text("""
                INSERT INTO webhook_config (org_id, url, secret, events)
                VALUES (:oid, :url, :secret, :events)
                RETURNING id
            """),
            {"oid": org_id, "url": req.url, "secret": secret, "events": req.events},
        ).fetchone()
        db.commit()
    except Exception:
        db.rollback()
        raise HTTPException(status_code=409, detail="Webhook URL already registered")

    return {
        "id": str(result[0]),
        "url": req.url,
        "secret": secret,
        "events": req.events,
        "warning": "Store this secret securely — it will not be shown again.",
    }


@router.delete("/v1/webhooks/{webhook_id}")
def delete_webhook(
    webhook_id: str,
    db: Session = Depends(get_db),
    org_id: str = Depends(verify_api_key),
):
    result = db.execute(
        text("DELETE FROM webhook_config WHERE id = :wid AND org_id = :oid RETURNING id"),
        {"wid": webhook_id, "oid": org_id},
    ).fetchone()
    if not result:
        raise HTTPException(status_code=404, detail="Webhook not found")
    db.commit()
    return {"deleted": True, "id": webhook_id}


# ── Manual scan trigger ──────────────────────────────────────────────────────

@router.post("/v1/scan")
def trigger_scan(
    db: Session = Depends(get_db),
    org_id: str = Depends(verify_api_key),
):
    """Trigger a manual proactive scan. Startup plan only."""
    from app.plan_enforcer import get_org_plan
    plan = get_org_plan(db, org_id)
    if plan["tier"] not in ("startup", "hustler"):
        raise HTTPException(status_code=403, detail="Proactive scanning requires Hustler or Startup plan")

    from app.tasks.proactive_scanner import run_proactive_scan
    result = run_proactive_scan(org_id)
    return {"scan_result": result}
