"""L2.4.8 · the ANOMALY DETECTOR (BLG-13) — is this node behaving unlike ITSELF?

Two units, one pipeline, the same shape the trend computer uses:

* **U1 `detect_anomaly`** — a series in, a typed `AnomalyVerdict` out. Pure: no database, no
  network, no clock, no model. Integer arithmetic end to end.
* **U2 `refresh_anomaly_facts`** — writes the verdict back as `derived.anomaly.<metric>` on the
  node so L3 and L4 read it like any other fact. Called from `context/runner.process_pending`,
  which is the sweep both API sync routes and the upload route already run.

**WHY THIS EXISTS BESIDE THE COHORT COMPARATOR.** A cohort answers *how does this account compare
to its peers*, and an account can sit in the top quartile of its cohort while collapsing against
its own six-month norm. That account is precisely the one a peer comparison never surfaces, and it
is the "at-risk flagged 30+ days early" case the product is sold on — the early signal comes from
a node's own baseline, not from the population.

**MAD, NOT STANDARD DEVIATION, AND THAT IS THE WHOLE DESIGN.** A standard deviation is defined by
squared error, so a single extreme reading widens the band in proportion to its own extremity —
the outlier inflates the dispersion until it sits inside it, which is exactly the reading an
anomaly detector exists to catch. A median absolute deviation moves by at most one rank when one
point moves arbitrarily far. `test_one_outlier_cannot_hide_inside_its_own_standard_deviation` is
the test that pins this: the same series, the same spike, sigma says "within 3σ" and MAD says
"22 MADs out".

**`z_like_bp` IS UNBOUNDED ON PURPOSE.** Doc 04 flags above 30000 — three times the top of the
0..10000 proportion range — so the contract validates it with `require_ratio_bp`, and nothing here
clamps it. A 40-MAD collapse must report as 40 MADs. A ceiling would render a catastrophe and a
bad Tuesday as the same number, which is the one thing the field is read for.

**BOTH CONDITIONS, ALWAYS** (`Z_LIKE_FLAG_BP` and `DEVIATION_FLAG_BP`). Statistically unusual is
not the same as materially large: a metric that normally sits at 2 going to 4 is many MADs out on
a series with almost no dispersion, and it is also nothing. The material floor is what stops the
detector filling a card with arithmetically impeccable trivia.

**SIX PERIODS OF BASELINE, ELSE A REFUSAL.** There is no anomaly without a normal to be anomalous
against, and `MIN_ANOMALY_PERIODS` is a CONTRACT rule (D-06) rather than a tunable here: `Anomaly`
itself refuses to be constructed with fewer. `INSUFFICIENT_HISTORY` is therefore a return value,
not an exception — a node with four months of data is not an error, it is a node we cannot say
this about yet, and the difference has to survive to the card.

**A GAP IS NOT A ZERO.** An unknown period is dropped from the baseline sample; it never
contributes a value and it is never interpolated. It reduces `periods_used`, which is what pushes
a sparse series toward `INSUFFICIENT_HISTORY` instead of toward a fabricated collapse. Doc 04
names "a coverage gap read as a drop" as the worst output this group can produce: a false churn
alarm about a real customer, generated by the tenant connecting one fewer mailbox.

**POINT-IN-TIME AND REPLAYABLE, ON BOTH SIDES OF THE PASS.** `eval_time` is a parameter with no
default and no fallback clock, every read is `as_at` that instant, and every number below is
integer arithmetic a reader can re-run by hand — so the same series at the same `eval_time` yields
a byte-identical verdict this morning, in September, and on a backfill.

And the WRITE is now point-in-time too, which it was not. U2 used to end its own upsert with
`valid_from = excluded.valid_from`, so September's sweep moved the window of March's row and
`read_graph(as_of=March)` answered "we knew nothing" about a verdict this module had published in
March. It publishes through `analytic/publish.publish_derived_fact` instead: `valid_from` never
moves, a verdict that has not changed writes nothing at all, and a verdict that changes in a later
week supersedes rather than overwrites. Doc 02's acceptance row — *replaying a March decision
against as_of=March reproduces its inputs* — is a property of this pass again.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta
from enum import Enum
from typing import Any, Sequence

from genios_engine.context.analytic.history import (HISTORY_TABLE, MetricDefinition, MetricGrain,
                                                    MetricRegistry, period_start)
from genios_engine.context.analytic.publish import publish_derived_fact
from genios_engine.contracts.analytic import (MIN_ANOMALY_PERIODS, Anomaly, AnomalyDirection,
                                              MetricPoint)
from genios_engine.contracts.validators import require_aware, require_identifier
from genios_engine.contracts.visibility import ORG

# =================================================================================================
# THE CONSTANTS THE ANSWER TURNS ON. Every one is a threshold a reviewer can argue with, so every
# one is named here rather than spelled inline at the comparison. MIN_ANOMALY_PERIODS is NOT among
# them — it is the contract's (D-06), imported, never re-declared.
# =================================================================================================

#: Doc 04 step 5, first condition: roughly three MADs. Compared with `>`, so a reading at exactly
#: three MADs is not an anomaly — the boundary belongs to normal, because a detector whose
#: threshold is inclusive fires on the most common value in the tail.
Z_LIKE_FLAG_BP = 30_000

#: Doc 04 step 5, second condition: 20% off the baseline. This is the one that stops a metric
#: which normally sits at 2 going to 4 from firing as a crisis — statistically unusual, materially
#: trivial. Also compared with `>`.
DEVIATION_FLAG_BP = 2_000

#: Doc 04 step 1: the baseline is the node's own TRAILING SIX periods, excluding the current one.
#: Six rather than "everything we hold" because the question is *unlike itself lately* — an
#: account that changed shape a year ago has a new normal, and averaging the old one back in
#: reports the change forever.
BASELINE_PERIODS = 6

#: How far back U2 reads to find six KNOWN periods. Twelve is double the baseline, so a series
#: half of which is holes still answers, and it bounds the dense read at twelve `MetricPoint`s per
#: (node, metric) rather than the whole retention window.
ANOMALY_WINDOW_PERIODS = 12

#: U2's per-sweep ceiling on (node, metric) pairs. The WRITE is bounded by the period-keyed
#: publish below — one row per (node, metric) per ISO week in which the verdict actually MOVED —
#: but the READ is one dense series each, and an org with 50k nodes would otherwise turn one
#: sweep into 50k series reads.
#:
#: **THE TAIL IS NO LONGER PERMANENT, and the sentence that used to stand here — "the pairs are
#: ordered, so the same sweep truncates at the same place every time" — was stating the defect as
#: a feature.** Ordered by id, an org above this budget cut the SAME pairs on EVERY sweep, for
#: ever: those nodes could never receive an anomaly verdict at all, and nothing in the drain's
#: return value said so. `_measured_pairs` now orders by STALENESS (never judged first, then the
#: oldest standing verdict), so the pairs one period's budget cuts are the pairs the next
#: period's sweep reads first, and `AnomalySweep.budget_exhausted` says out loud that a tail
#: exists. Determinism is kept where it is worth having: the order is a function of the stored
#: facts and `eval_time` only, so a replayed sweep still selects the same pairs.
MAX_ANOMALY_FACTS_PER_SWEEP = 2_000

#: The `graph_facts.field` prefix. `derived.*` is the namespace every computed fact in L2 writes
#: into (`derived.trend.*`, `derived.engagement`), so L3's readers already walk it.
ANOMALY_FACT_PREFIX = "derived.anomaly."

#: `graph_facts.value_type` for the object U2 writes: a JSON document, because a verdict split
#: across six scalar facts is six rows a reader must re-assemble and any one of which can go stale
#: on its own.
ANOMALY_VALUE_TYPE = "json"

#: The `fact_version_id` prefix this module owns. `publish_derived_fact` keys the rest of the id
#: on (node, field, PERIOD), and this prefix is what scopes its open-row lookup and its close, so
#: U2 can only ever supersede a row U2 wrote. Rows written under the old period-less shape
#: (`fv_anomaly_<node>_<field>`) still begin with it and are absorbed rather than orphaned.
ANOMALY_VERSION_PREFIX = "fv_anomaly_"

#: The audience of an anomaly fact — **stated, because `publish_derived_fact` refuses to default
#: it.** `contracts/visibility` sets the law all four L2.4 writers were quietly widening when they
#: spelled `'org'` inline: *the audience of a derived insight can never be wider than the audience
#: of the evidence it came from.*
#:
#: THE LINE THIS MODULE APPLIES: a derived row's audience is set by WHAT THE ROW CARRIES, not by
#: the ultimate provenance of the numbers in it. The other reading — trace every input to the mail
#: it came from — makes every fact in the graph `private` and turns the column into a constant
#: that says nothing.
#:
#: `ORG` is the right answer for THIS fact, and it is the one of the four for which that is true
#: without argument. A verdict is a statement about ONE node measured against ITS OWN trailing
#: series: no peer's reading, no cohort, no other node's name, and — unlike the two correlation
#: writers, which republish sentences lifted out of somebody's mail — no quoted text at all.
#: `anomaly_fact_value` carries numbers plus a POINTER back to `metric_history` (node, metric,
#: unit, first/last period) and deliberately leaves the evidence values out. That is
#: `context/derived.py`'s defensible case exactly: a fact that describes the subject alone is as
#: visible as the subject, and anyone in the tenant may already open the node it is about.
ANOMALY_VISIBILITY_SCOPE = ORG


# =================================================================================================
# INTEGER ARITHMETIC. No float appears in this module, including as an intermediate.
# =================================================================================================

def _median(values: Sequence[int]) -> int:
    """The median of a non-empty integer sample. Integer in, integer out, no float anywhere.

    An even-sized sample has two middle values, and the two integer-exact ways to resolve them are
    not equivalent here. Taking the LOWER middle is order-stable but it is BIASED, and a baseline
    is exactly where that bias bites: on a genuinely two-humped series — a metric that alternates
    between 100 and 300 — the lower middle reports the normal as 100, which then makes every high
    period look like a deviation of 200 and turns a node's ordinary swing into a standing anomaly.
    The floor of the two middles' mean (`(a + b) // 2`) sits between the humps where the normal
    actually is.

    Floor rather than round-half-up because floor is a total rule with no tie case, so a replayed
    verdict is byte-identical rather than merely close, and because the same rule is applied to the
    baseline and to the MAD — a rule with a tie case would resolve the two inconsistently and the
    ratio between them is the number the flag turns on.
    """
    if not values:
        raise ValueError("a median needs at least one value")
    ordered = sorted(values)
    middle = len(ordered) // 2
    if len(ordered) % 2:
        return ordered[middle]
    return (ordered[middle - 1] + ordered[middle]) // 2


def _ratio_bp(numerator: int, denominator: int) -> int:
    """`numerator * 10000 // max(denominator, 1)` — a non-negative ratio in basis points.

    Both arguments are magnitudes by the time they reach here. `max(denominator, 1)` is doc 04's
    own guard and it is doing real work twice: a baseline of zero (a metric that has read zero all
    six periods) and a MAD of zero (a perfectly flat series) are both ordinary, and both would
    otherwise divide by zero on the first reading that moved. Flooring at one makes the ratio
    read "the whole of the movement, in units of the smallest dispersion we can distinguish",
    which is the honest answer for a series with no width.
    """
    if numerator < 0 or denominator < 0:
        raise ValueError("both sides of a ratio in basis points are magnitudes")
    return numerator * 10_000 // max(denominator, 1)


# =================================================================================================
# THE REFUSALS. First-class return values, not exceptions and not a weak answer.
# =================================================================================================

class AnomalyRefusal(str, Enum):
    """Why no verdict could be reached. A refusal is INFORMATION and it must reach the card.

    Returning a weak anomaly where the contract says refuse is the defect this stratum is built to
    avoid: an "unusual" computed from three readings is a statement about the sample size wearing
    the clothes of a statement about the business, and the reader cannot tell them apart.
    """

    #: Fewer than `MIN_ANOMALY_PERIODS` KNOWN periods before the current reading. There is no
    #: anomaly without a normal to be anomalous against.
    INSUFFICIENT_HISTORY = "insufficient_history"
    #: The series ends on a period we have no reading for. A gap is not a zero, so there is
    #: nothing to judge — and judging the last KNOWN reading instead would silently date the
    #: verdict to whenever that was.
    NO_CURRENT_READING = "no_current_reading"


@dataclass(frozen=True)
class AnomalyVerdict:
    """What U1 returns: the measurement, and whether it cleared BOTH flags — or why it could not.

    **The un-flagged measurement is carried, not discarded.** A verdict of "measured, 1.4 MADs
    out, 3% off baseline" is what lets a reader ask *why wasn't this flagged* and get an answer,
    and it is what U2 writes over last sweep's anomaly when a node returns to normal. A detector
    that returned `None` for everything below the threshold would leave every retraction invisible.

    `anomaly` is populated IFF `flagged`, because `Anomaly` is the contract's object for a thing
    that IS anomalous and building one for a quiet metric would put a guaranteed row in front of
    every real finding.
    """

    metric: str
    #: `None` when the verdict is a refusal — there is no reading to report.
    current_bp: int | None
    baseline_bp: int | None
    mad_bp: int | None
    deviation_bp: int | None
    z_like_bp: int | None
    direction: AnomalyDirection | None
    #: KNOWN periods in the baseline, excluding the current reading.
    periods_used: int
    flagged: bool
    anomaly: Anomaly | None
    refusal: AnomalyRefusal | None
    #: The exact points the baseline was taken from, oldest first, plus the current reading last.
    #: The receipt: "which six months is this compared against" is answerable without a re-query.
    evidence_points: tuple[MetricPoint, ...]

    @property
    def answered(self) -> bool:
        """A measurement was taken. Says nothing about whether it was anomalous."""
        return self.refusal is None


def _refusal(metric: str, reason: AnomalyRefusal, periods_used: int,
             evidence: tuple[MetricPoint, ...]) -> AnomalyVerdict:
    """A refusal carries no numbers. Not tidiness: a baseline computed from four points and
    reported beside the word "insufficient" is a number that gets read and quoted anyway."""
    return AnomalyVerdict(metric=metric, current_bp=None, baseline_bp=None, mad_bp=None,
                          deviation_bp=None, z_like_bp=None, direction=None,
                          periods_used=periods_used, flagged=False, anomaly=None,
                          refusal=reason, evidence_points=evidence)


# =================================================================================================
# U1 · DEVIATION FROM A NODE'S OWN BASELINE
# =================================================================================================

def detect_anomaly(series: Sequence[MetricPoint], *,
                   baseline_periods: int = BASELINE_PERIODS,
                   min_periods: int = MIN_ANOMALY_PERIODS) -> AnomalyVerdict:
    """Doc 04 L2.4.8-U1, step by step, on a series ordered oldest period first.

    ```
    1. baseline  = median of the node's own trailing 6 KNOWN periods (excluding current)
    2. dispersion= median absolute deviation about that baseline — integer, robust to outliers
    3. deviation_bp = |current - baseline| * 10000 // max(|baseline|, 1)
    4. z_like_bp    = |current - baseline| * 10000 // max(mad, 1)
    5. flag if z_like_bp > 30000 AND deviation_bp > 2000
    6. require >= 6 known baseline periods, else INSUFFICIENT_HISTORY
    ```

    **The current reading is the LAST POINT OF THE SERIES, and it must be known.** Reaching back
    for the most recent known reading instead would silently answer a question about March with
    July's number and stamp it with today's period — the same fault as a gap read as a zero, one
    level up. A trailing gap is `NO_CURRENT_READING`, which is a true statement about the series.

    **`min_periods` is a parameter and it cannot loosen the contract.** Passing fewer than
    `MIN_ANOMALY_PERIODS` still refuses: `Anomaly` will not be constructed below D-06's floor, so
    a caller who lowered it here would get an exception on the flagged path instead of the weak
    answer they asked for. The parameter exists to make the floor TIGHTER on a noisy metric.
    """
    points = tuple(series)
    if not points:
        return _refusal("unknown", AnomalyRefusal.INSUFFICIENT_HISTORY, 0, ())

    metric = points[-1].metric
    floor = max(min_periods, MIN_ANOMALY_PERIODS)

    current = points[-1]
    if not current.known or current.value_bp is None:
        # A gap is not a zero, and it is not a reading either. Count what we DO hold so the
        # refusal can say how close the series is to answering.
        known_before = sum(1 for point in points[:-1] if point.known)
        return _refusal(metric, AnomalyRefusal.NO_CURRENT_READING, known_before, points[-1:])

    # Step 1 — the trailing baseline. Gaps drop out of the sample rather than contributing a
    # value; `[-baseline_periods:]` is applied AFTER the drop, so six known readings behind three
    # months of holes still form a baseline and three known readings do not.
    prior = [point for point in points[:-1] if point.known and point.value_bp is not None]
    window = prior[-baseline_periods:] if baseline_periods > 0 else []
    if len(window) < floor:
        return _refusal(metric, AnomalyRefusal.INSUFFICIENT_HISTORY, len(window),
                        tuple(window) + (current,))

    values = [point.value_bp for point in window if point.value_bp is not None]
    baseline = _median(values)

    # Step 2 — MAD about that baseline, never a standard deviation. See the module docstring.
    mad = _median([abs(value - baseline) for value in values])

    # Steps 3 and 4. `delta` is a magnitude; the sign is carried by `direction` as a word.
    delta = abs(current.value_bp - baseline)
    deviation_bp = _ratio_bp(delta, abs(baseline))
    z_like_bp = _ratio_bp(delta, mad)
    direction = (AnomalyDirection.ABOVE if current.value_bp >= baseline
                 else AnomalyDirection.BELOW)

    # Step 5 — BOTH conditions. Unusual and material, never one of the two.
    flagged = z_like_bp > Z_LIKE_FLAG_BP and deviation_bp > DEVIATION_FLAG_BP
    evidence = tuple(window) + (current,)
    anomaly = None
    if flagged:
        anomaly = Anomaly(metric=metric, current_bp=current.value_bp, baseline_bp=baseline,
                          mad_bp=mad, deviation_bp=deviation_bp, z_like_bp=z_like_bp,
                          direction=direction, periods_used=len(window))
    return AnomalyVerdict(metric=metric, current_bp=current.value_bp, baseline_bp=baseline,
                          mad_bp=mad, deviation_bp=deviation_bp, z_like_bp=z_like_bp,
                          direction=direction, periods_used=len(window), flagged=flagged,
                          anomaly=anomaly, refusal=None, evidence_points=evidence)


# =================================================================================================
# U2 · THE VERDICT AS A GRAPH FACT — the wiring, and the reason U1 is reachable at all
# =================================================================================================

def anomaly_fact_field(metric: str) -> str:
    """`derived.anomaly.<metric>` — the `graph_facts.field` a verdict is written under.

    One field per metric rather than one `derived.anomaly` blob per node: L3's readers select on
    `field`, and a blob would make "is engagement anomalous" a read of every metric the node has.
    """
    return f"{ANOMALY_FACT_PREFIX}{require_identifier(metric, 'metric')}"


def anomaly_fact_value(verdict: AnomalyVerdict) -> dict[str, Any]:
    """The JSON body: the verdict, its numbers, and the pointer back to the series.

    The pointer is `(subject_node_id, metric, first_period, last_period)` — `metric_history`'s
    primary key minus the ambient tenant — so "which six months said this was abnormal" is a query
    a reader can run. The evidence VALUES are deliberately not copied in: they are already rows in
    a table built to be read across time, and a second copy in `graph_facts` is a second thing to
    keep in step with retention.
    """
    body: dict[str, Any] = {
        "metric": verdict.metric,
        "flagged": verdict.flagged,
        "refusal": verdict.refusal.value if verdict.refusal else None,
        "current_bp": verdict.current_bp,
        "baseline_bp": verdict.baseline_bp,
        "mad_bp": verdict.mad_bp,
        "deviation_bp": verdict.deviation_bp,
        "z_like_bp": verdict.z_like_bp,
        "direction": verdict.direction.value if verdict.direction else None,
        "periods_used": verdict.periods_used,
    }
    if verdict.evidence_points:
        first, last = verdict.evidence_points[0], verdict.evidence_points[-1]
        body["series"] = {
            "subject_node_id": last.subject_node_id,
            "metric": verdict.metric,
            "unit": last.unit.value,
            "first_period": first.observed_at.isoformat(),
            "last_period": last.observed_at.isoformat(),
            "periods": len(verdict.evidence_points),
        }
    return body


def _window_start(eval_time: datetime, grain: MetricGrain, periods: int) -> datetime:
    """The boundary `periods - 1` periods before `eval_time`'s period. No calendar library.

    Month arithmetic goes through `period_start` so a 31st never lands on a phantom boundary;
    weeks are seven days, exactly as `history.next_period` adds them.
    """
    start = period_start(require_aware(eval_time, "eval_time"), grain)
    if grain is MetricGrain.WEEK:
        return start - timedelta(days=7 * (periods - 1))
    year, month = divmod(start.year * 12 + (start.month - 1) - (periods - 1), 12)
    return start.replace(year=year, month=month + 1, day=1)


#: The pair queue, ordered by HOW STALE EACH PAIR'S VERDICT IS. Three keys, and the first one is
#: the guarantee: a pair with no open verdict outranks every pair that has one, so no (node,
#: metric) this org has history for can be dark for ever — which is exactly what `order by
#: subject_node_id, metric limit 2000` did to every pair past the budget.
#:
#:   1. `f.occurred_at is null` — never judged (or judged and since retired). Always first.
#:   2. oldest `occurred_at` — the instant of the sweep that last MOVED this pair's verdict.
#:      `publish_derived_fact` stamps it on every write and writes NOTHING when the verdict is
#:      unchanged, so it reads as "when did we last have something new to say about this pair".
#:   3. (node, metric) — a total order, so a replay of one sweep picks the same pairs.
#:
#: KEY 2 IS SELF-CORRECTING ACROSS PERIODS rather than merely fair-looking, and that turns on a
#: property of the body: `anomaly_fact_value` carries `series.last_period`, which is the period
#: `eval_time` falls in. So the FIRST sweep of a new period necessarily publishes a changed body
#: for every pair it reads, `occurred_at` advances to that sweep, and those pairs drop behind the
#: ones the previous period's budget could not reach. Within one period the selection is stable —
#: identical body, nothing written, nothing moves — which is the determinism a budget wants;
#: across periods the queue rotates, which is the coverage the id order never had.
#:
#: The join is `valid_to is null and status = 'active'`, which is precisely the partial index
#: `graph_facts_current (org_id, subject_node_id, field)`, so the ordering costs a sort of this
#: org's pairs rather than a scan of the graph.
_STALE_PAIRS_SQL = (
    "select h.subject_node_id as subject_node_id, h.metric as metric "
    f"from (select distinct subject_node_id, metric from {HISTORY_TABLE} where org_id = :o) h "
    "left join graph_facts f on f.org_id = :o and f.subject_node_id = h.subject_node_id "
    "  and f.field = :fp || h.metric and f.valid_to is null and f.status = 'active' "
    "order by (f.occurred_at is null) desc, f.occurred_at asc, "
    "         h.subject_node_id, h.metric limit :n")


def _measured_pairs(store, org_id: str, limit: int) -> tuple[list[tuple[str, str]], bool]:
    """The pairs this sweep will judge, stalest first, and whether the budget cut any of them.

    Read off `metric_history` rather than off the node table: the sampler's policy (BLG-07) has
    already decided which nodes and metrics are worth a series, and re-deriving that decision here
    would be a second copy of it that can disagree with the first. A pair with no points cannot
    produce a verdict anyway.

    `limit + 1` rows are read, and the extra one is thrown away, so the caller can report
    `budget_exhausted` HONESTLY. A sweep that read exactly `limit` pairs cannot otherwise tell
    "that was all of them" from "there are more, and this org has a tail it never hears about" —
    and it was the second of those, unsaid, that made the truncation invisible for as long as it
    was permanent.
    """
    from sqlalchemy import text

    with store.engine.connect() as conn:
        rows = conn.execute(text(_STALE_PAIRS_SQL),
                            {"o": org_id, "fp": ANOMALY_FACT_PREFIX, "n": limit + 1}).all()
    return ([(row.subject_node_id, row.metric) for row in rows[:limit]], len(rows) > limit)


@dataclass(frozen=True, slots=True)
class AnomalySweep:
    """What one drain's anomaly pass did — including WHERE IT STOPPED.

    U2 used to return a bare row count, and a count cannot tell "judged every pair this org has"
    from "judged the two thousand stalest and never mentioned the rest". `budget_exhausted` is
    that difference, and `context/runner.process_pending` puts it in the drain's return value so
    an org above budget is VISIBLE rather than quiet — the other half of the D9 fix, because the
    rotation above means the tail is served eventually and an operator still has to be able to see
    that a tail exists at all.

    `facts_written` counts the pairs whose verdict actually changed the database; `unchanged`
    counts the ones whose open row already said exactly this. Under `publish_derived_fact` a
    re-confirmation writes NOTHING — not even an `occurred_at` touch — and counting those as
    writes is how the old writer's amplification stayed invisible in the numbers.
    """

    pairs: int = 0
    facts_written: int = 0
    unchanged: int = 0
    budget_exhausted: bool = False

    @property
    def facts(self) -> int:
        """Every pair that reached a verdict this sweep, written or re-confirmed."""
        return self.facts_written + self.unchanged


def refresh_anomaly_facts(store, org_id: str, *, eval_time: datetime,
                          history: Any = None, registry: MetricRegistry | None = None,
                          window_periods: int = ANOMALY_WINDOW_PERIODS,
                          limit: int = MAX_ANOMALY_FACTS_PER_SWEEP) -> AnomalySweep:
    """U2 — recompute every verdict this org has history for and write it back.

    Called from `context/runner.process_pending`, immediately after the sampler that produced the
    points and the trend that reads the same series. Here rather than on a schedule for the reason
    the whole layer prefers: the Celery broker is a quota-limited Upstash instance, and the drain
    is the only thing that knows an org is active.

    **REFUSALS AND QUIET METRICS ARE WRITTEN TOO, and that is deliberate.** The cheap-looking
    alternative — write only the flagged ones — leaves last week's anomaly sitting on a node that
    has since returned to normal, and nothing ever retracts it. Publishing the un-flagged verdict
    supersedes it with "measured, within band", so the fact self-corrects on the next sweep.

    **THE WRITE GOES THROUGH `publish_derived_fact`, WHICH IS THE POINT-IN-TIME FIX.** This module
    used to end its own upsert with `valid_from = excluded.valid_from`, and that one assignment
    MOVED the window of a row that already existed: a verdict published in March and re-swept in
    September read back as `[September, inf)`, so `read_graph(as_of=March)` returned NOTHING about
    a fact GeniOS itself had published in March — and doc 02's acceptance row, *"replaying a March
    decision against as_of=March reproduces its inputs"*, failed for exactly the facts this pass
    exists to produce. The shared writer never moves `valid_from`: an unchanged verdict writes
    nothing at all, a verdict that moves inside one ISO week is corrected in place, and a verdict
    that moves in a LATER week closes March's row and opens a new one — so March keeps its answer
    and the timeline reads as two stints instead of one lie.

    `eval_time` is a parameter with no default and no fallback clock. It is the `as_at` horizon of
    every read, the end of every window, and the `valid_from` of every row opened, so a verdict
    computed for a past instant uses only what was known then — which is the entire reason the
    history store records `sampled_at` separately from `observed_at`.
    """
    from genios_engine.context.analytic.sampler import resolve_history_store, sampler_registry

    at = require_aware(eval_time, "eval_time")
    registry = registry or sampler_registry()
    history = history if history is not None else resolve_history_store(store)

    facts: list[tuple[str, str, dict[str, Any]]] = []
    pairs, exhausted = _measured_pairs(store, org_id, limit)
    for node_id, metric in pairs:
        definition: MetricDefinition | None = registry.get(metric)
        if definition is None:
            continue          # written under a name this process does not define; not ours to read
        series = history.read_series(
            org_id, node_id, metric,
            since=_window_start(at, definition.grain, window_periods), until=at, as_at=at)
        if not series:
            continue
        verdict = detect_anomaly(series)
        facts.append((node_id, anomaly_fact_field(metric), anomaly_fact_value(verdict)))

    if not facts:
        return AnomalySweep(pairs=len(pairs), budget_exhausted=exhausted)
    written = unchanged = 0
    # ONE transaction for the whole sweep, as before: `publish_derived_fact` takes the connection
    # the caller already owns, so a close and the insert that replaces it commit together and a
    # sweep can never retire the old verdict and then fail to write the new one.
    with store.engine.begin() as conn:
        for node_id, field_name, value in facts:
            published = publish_derived_fact(
                conn, org_id=org_id, subject_node_id=node_id, field=field_name, value=value,
                eval_time=at, value_type=ANOMALY_VALUE_TYPE,
                visibility_scope=ANOMALY_VISIBILITY_SCOPE,
                version_prefix=ANOMALY_VERSION_PREFIX,
                # `fact_id` keeps the shape it has always had. `fact_version_id` is now
                # period-keyed, so `fact_id` is the only column left that says "these rows are
                # successive versions of ONE fact" — and `graph_facts_by_fact` is the index a
                # reader walks to find them.
                fact_id=f"f_anomaly_{node_id}_{field_name}")
            if published.wrote:
                written += 1
            else:
                unchanged += 1
    return AnomalySweep(pairs=len(pairs), facts_written=written, unchanged=unchanged,
                        budget_exhausted=exhausted)


__all__ = ["ANOMALY_FACT_PREFIX", "ANOMALY_VALUE_TYPE", "ANOMALY_VERSION_PREFIX",
           "ANOMALY_VISIBILITY_SCOPE", "ANOMALY_WINDOW_PERIODS",
           "BASELINE_PERIODS", "DEVIATION_FLAG_BP", "MAX_ANOMALY_FACTS_PER_SWEEP",
           "Z_LIKE_FLAG_BP", "AnomalyRefusal", "AnomalySweep", "AnomalyVerdict",
           "anomaly_fact_field", "anomaly_fact_value", "detect_anomaly", "refresh_anomaly_facts"]
