"""L2.4.3 · the TREND COMPUTER (BLG-08) — the first function in GeniOS that can say "declining".

Three units live here and they are one pipeline:

* **U1 `compute_trend`** — a dense series in, a typed `Trend` out. Pure: no database, no network,
  no clock, no model. Integer arithmetic end to end.
* **U2 `find_changepoint`** — *"since March"* rather than *"declining"*. The longest suffix whose
  direction differs from the prefix, both segments held to the same four-point floor.
* **U3 `refresh_trend_facts`** — writes the answer back as `derived.trend.<metric>` on the node so
  L3 and L4 read it like any other fact. Called from `context/runner.process_pending`, which is
  the sweep both API sync routes and the upload route already run.

**WHY THE MEASUREMENT REFUSES TO USE A MODEL.** A trend is a comparison of a business against its
own past, and a comparison needs a stable instrument. If March's reading and September's reading
came from a language model, a disagreement between them could be attributed neither to the
business nor to the model — which makes the reading worthless in the only situation where anyone
cares. Every number below is an integer computed by a formula a reader can re-run by hand.

**THE TWO REFUSALS ARE THE PRODUCT.** `INSUFFICIENT_HISTORY` and `INSUFFICIENT_COVERAGE` are
return values, not errors. Doc 04 names "a coverage gap read as decline" as *the worst output this
group can produce* — a false churn alarm about a real customer, generated by the tenant connecting
one fewer mailbox. A gap is never a zero here, never interpolated, and it counts AGAINST the
coverage ratio rather than silently improving it.

**TWO SLOPES, AND WHY** (see `_ls_slope_scaled` / `_robust_slope_scaled`). Doc 04 step 2 prescribes
integer least squares, and doc 04's own acceptance list also requires that *"a single huge outlier
at the end does not flip a 10-point flat series to RISING"*. Those two requirements contradict
each other: least squares is defined by squared error, so one reading a thousand times the base
dominates the fit completely — the arithmetic is worked through in `_robust_slope_scaled`. Both
are therefore computed. The **median of pairwise slopes** (Theil-Sen, integer, O(n^2) over a
series the retention cap holds to 104 points) is the reported estimator, and the least-squares
slope must AGREE with it in sign and magnitude before any direction is claimed. A single point can
move the least-squares line arbitrarily far; it can move a median by one rank.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Any, Sequence

from genios_engine.context.analytic.history import (MetricDefinition, MetricGrain, MetricRegistry,
                                                    period_start)
from genios_engine.contracts.analytic import (DIRECTIONAL, MAX_TREND_CONFIDENCE_BP,
                                              MIN_TREND_POINTS, NON_ANSWERS, MetricPoint, Trend,
                                              TrendDirection)
from genios_engine.contracts.validators import require_aware, require_identifier

# =================================================================================================
# THE CONSTANTS THE ANSWER TURNS ON. Every one of them is a threshold a reviewer can argue with,
# so every one of them is named here rather than spelled inline at the comparison.
# =================================================================================================

#: Doc 04 step 4. A move of less than 5% of the base per period is not a direction, it is noise
#: with a sign. Applied to the NORMALISED slope, never to the raw one — see step 3.
DIRECTION_THRESHOLD_BP = 500

#: Doc 04 step 1. A series more than 40% holes cannot support a trend claim: the fit would be
#: describing the periods we happened to observe, and the reader has no way to see that from the
#: word "declining". Compared with `<`, so a series exactly 60% known still answers.
COVERAGE_FLOOR_BP = 6_000

#: The point count at which the count component of confidence saturates. Twelve monthly readings
#: is a year; nothing beyond it makes the extrapolation more honest, and the cap is what stops a
#: 104-point series from reaching confidence a four-point one is denied.
CONFIDENT_POINTS = 12

#: How far back U3 reads when it refreshes the facts. Twelve periods is a year of months or a
#: quarter of weeks, it is three times BLG-08's floor, and it bounds the dense read: the series
#: materialised per (node, metric) is twelve `MetricPoint`s, not the whole retention window.
TREND_WINDOW_PERIODS = 12

#: U3's per-sweep ceiling on (node, metric) pairs. The write itself is bounded by construction —
#: one version-keyed row per pair, overwritten forever — but the READ is one dense series each,
#: and an org with 50k nodes would otherwise turn one sweep into 50k series reads. Deterministic
#: tail: the pairs are ordered, so the same sweep truncates at the same place and the next sweep
#: (after the sampler has moved the series) covers what this one did.
MAX_TREND_FACTS_PER_SWEEP = 2_000

#: The `graph_facts.field` prefix. `derived.*` is the namespace every computed fact in L2 writes
#: into (`derived.engagement`, `derived.stage`), so L3's readers already walk it.
TREND_FACT_PREFIX = "derived.trend."

#: `graph_facts.value_type` for the object U3 writes. The value is a JSON document — direction,
#: strength, coverage and the series pointer — because a trend split across six scalar facts is
#: six rows a reader has to re-assemble and any one of which can go stale on its own.
TREND_VALUE_TYPE = "json"


# =================================================================================================
# INTEGER ARITHMETIC. No float appears in this module, including as an intermediate.
# =================================================================================================

def _idiv(numerator: int, denominator: int) -> int:
    """Integer division that TRUNCATES TOWARD ZERO, unlike Python's `//`.

    `//` floors, so `-1 // 3` is `-1` while `1 // 3` is `0`. On a slope that asymmetry is not
    cosmetic: it biases every small negative move one unit further from zero than the mirror-image
    positive move, so a series and its negation do not produce mirror-image trends, and at the
    `DIRECTION_THRESHOLD_BP` boundary the two signs cross at different magnitudes. Truncation
    toward zero makes `compute_trend(-series)` the exact negation of `compute_trend(series)`,
    which is the property the sign-inversion mutation test rests on.
    """
    if denominator == 0:
        raise ZeroDivisionError("integer division by zero in the trend arithmetic")
    quotient = abs(numerator) // abs(denominator)
    return -quotient if (numerator < 0) != (denominator < 0) else quotient


def _clamp_bp(value: int) -> int:
    """Hold a normalised slope inside the contract's signed basis-point range.

    `Trend.relative_slope_bp` is validated by `require_signed_bp` at -10000..10000, and a series
    that halves every period legitimately computes past that. Clamping rather than raising: a
    metric falling faster than its own base per period is a real reading, and the rail is the
    honest rendering of "off the scale in this direction" — refusing to build the object would
    turn the most extreme decline in the tenant's data into an exception on the sweep.
    """
    return max(-10_000, min(10_000, value))


def _lower_median(values: Sequence[int]) -> int:
    """The lower median of an already-sortable list. Deterministic on an even count.

    The lower of the two middles rather than their mean: the mean of two integers is not an
    integer, and rounding it would put a value in the output that is not one of the pairwise
    slopes actually observed.
    """
    ordered = sorted(values)
    return ordered[(len(ordered) - 1) // 2]


# =================================================================================================
# U1 · DIRECTION AND MAGNITUDE
# =================================================================================================

def _known_pairs(series: Sequence[MetricPoint]) -> list[tuple[int, int]]:
    """`(period_index, value)` for every point that carries a reading.

    The index is the position in the DENSE series, not the position among the known points. That
    distinction is the whole gap discipline in one line: a reading two periods after its
    predecessor is plotted two units along, so a hole widens the spacing instead of vanishing and
    pulling the later readings backwards into a steeper slope.
    """
    return [(index, point.value_bp) for index, point in enumerate(series)
            if point.known and point.value_bp is not None]


def _ls_slope_scaled(pairs: Sequence[tuple[int, int]]) -> int:
    """Doc 04 step 2, exactly: `(n*Sxy - Sx*Sy) * 10000 // (n*Sxx - Sx*Sx)`.

    Scaled by 10000 so the sub-unit slopes that matter most survive — "one touch fewer every three
    months" is a slope of -1/3, and an unscaled integer division would report it as zero. Multiply
    before dividing, which is doc 04's fourth failure mode.

    The denominator is `n * sum(x^2) - sum(x)^2`, which is zero only when every known point sits
    at the same period index. Two points cannot share an index — the index IS the period — so this
    is unreachable above one known point, and one known point cannot get here at all (`n >= 4`).
    """
    n = len(pairs)
    sx = sum(x for x, _ in pairs)
    sy = sum(y for _, y in pairs)
    sxx = sum(x * x for x, _ in pairs)
    sxy = sum(x * y for x, y in pairs)
    return _idiv((n * sxy - sx * sy) * 10_000, n * sxx - sx * sx)


def _robust_slope_scaled(pairs: Sequence[tuple[int, int]]) -> int:
    """The median of every pairwise slope, scaled by 10000. Theil-Sen, in integers.

    **This is the estimator the direction is read off, and it exists because doc 04's own
    acceptance list contains a row least squares cannot satisfy.** Take the doc's case: nine
    readings of 100 and a tenth of 100000. Least squares returns a slope of +5449 per period on a
    base of 10090 — a normalised +5400 bp, eleven times the direction threshold — and the series
    is reported RISING on the strength of one number. That is not a tuning problem; squared error
    is *defined* to let one distant point dominate.

    The median of the 45 pairwise slopes for the same series is 0: thirty-six of the pairs are
    flat and only nine touch the outlier, so the outlier moves the answer by nine ranks and not at
    all in value. One point can move a least-squares line arbitrarily far; it can move a median
    by one rank. Both are computed and both must agree before a direction is claimed.

    O(n^2), which is 5356 pairs at the retention cap of 104 points and typically 66 at the twelve
    U3 reads. There is no series in this system where that is a cost worth trading honesty for.
    """
    slopes = [_idiv((later_y - early_y) * 10_000, later_x - early_x)
              for index, (early_x, early_y) in enumerate(pairs)
              for later_x, later_y in pairs[index + 1:]]
    return _lower_median(slopes) if slopes else 0


def _base_value(pairs: Sequence[tuple[int, int]]) -> int:
    """Doc 04 step 3's denominator: the mean MAGNITUDE of the known readings, floored at 1.

    **Step 3 is the one people skip and it is what makes the word "declining" comparable across
    metrics.** A drop of five means nothing on a base of 5000 and everything on a base of 8; an
    absolute slope shared between `engagement.touch_count` and `deal.value_minor_units` is two
    incomparable numbers wearing one field name.

    Magnitude rather than the signed mean, which is a deliberate departure from `max(mean, 1)` as
    written: a differenced or delta metric runs negative, its signed mean is negative, `max(.., 1)`
    collapses the base to 1, and every slope on it normalises to the clamp rail. The magnitude
    mean is the same number on every non-negative series — which is all twelve registered metrics
    — and is the scale of the series on the rest.

    The floor at 1 is what makes an all-zero series return FLAT instead of a `ZeroDivisionError`.
    """
    return max(_idiv(sum(abs(value) for _, value in pairs), len(pairs)), 1)


def _direction(robust_relative_bp: int, ls_relative_bp: int) -> TrendDirection:
    """Doc 04 step 4, over BOTH normalised slopes. Disagreement is FLAT.

    Requiring agreement is a one-way ratchet toward refusal: it can only ever turn a direction
    into FLAT, never manufacture one. That is the correct asymmetry — a missed decline costs a
    card that could have been shown, and a fabricated decline is a false churn alarm about a real
    customer who is fine.
    """
    if robust_relative_bp > DIRECTION_THRESHOLD_BP and ls_relative_bp > DIRECTION_THRESHOLD_BP:
        return TrendDirection.RISING
    if robust_relative_bp < -DIRECTION_THRESHOLD_BP and ls_relative_bp < -DIRECTION_THRESHOLD_BP:
        return TrendDirection.DECLINING
    return TrendDirection.FLAT


def _streak(series: Sequence[MetricPoint], direction: TrendDirection) -> int:
    """Doc 04 step 5 — consecutive PERIODS moving in the trend's direction, counted from the end.

    Counted in points rather than in steps, which is what doc 09's "a monotonic decline over 6
    points -> streak=6" asks for: five consecutive down-moves are six periods of decline.

    **A GAP ENDS THE RUN.** Two known readings either side of a hole are not consecutive periods,
    and calling them one run is the interpolation this module refuses, moved from the value into
    the count. Trailing gaps are skipped rather than zeroing the run — the run is a true statement
    about the series that ends at the last period we actually read.

    FLAT reports 0. There is no direction to move in, so any number here would be a run of
    something the field does not name; a reader who wants "steady for six months" has
    `point_count` and `coverage_ratio_bp`, which say it without inventing a unit.
    """
    if direction not in DIRECTIONAL:
        return 0
    rising = direction is TrendDirection.RISING
    index = len(series) - 1
    while index >= 0 and not series[index].known:
        index -= 1
    if index < 0:
        return 0
    run = 1
    while index >= 1 and series[index - 1].known:
        later, earlier = series[index].value_bp, series[index - 1].value_bp
        if later is None or earlier is None:
            break
        if (later > earlier) is not rising or later == earlier:
            break
        run += 1
        index -= 1
    return run


def _dispersion_bp(pairs: Sequence[tuple[int, int]], slope_scaled: int, base: int) -> int:
    """Mean absolute residual around the least-squares line, as basis points of the base.

    This is the "residual_dispersion" term doc 04 names in step 6 and never defines. Mean absolute
    deviation rather than a standard deviation: a square root has no integer answer, and the
    absolute residual is the quantity a reader can check against the printed series.

    Everything stays multiplied by 10000 — `slope_scaled` already is — so the division into basis
    points of the base happens exactly once, at the end.
    """
    n = len(pairs)
    sx = sum(x for x, _ in pairs)
    sy = sum(y for _, y in pairs)
    intercept_scaled = _idiv(sy * 10_000 - slope_scaled * sx, n)
    total = sum(abs(value * 10_000 - (intercept_scaled + slope_scaled * index))
                for index, value in pairs)
    return _idiv(_idiv(total, n), base)


def _confidence_bp(*, point_count: int, coverage_ratio_bp: int, streak_periods: int,
                   dispersion_bp: int) -> int:
    """Doc 04 step 6: `f(point_count, coverage_ratio, streak_length, residual_dispersion)`, capped.

    Four components, each already in basis points, combined on fixed integer weights and then
    scaled INTO the cap rather than clipped at it. Scaling matters: a `min(x, 8000)` would make
    every well-supported trend report exactly 8000 and destroy the ordering between a twelve-point
    full-coverage series and a four-point one at the moment a ranker needs it most. Here the
    ceiling is reachable only by a series that is saturated on all four components at once, and
    `MAX_TREND_CONFIDENCE_BP` is structurally unexceedable — V-4 holds by construction, not by a
    check the next editor can move.

    The weights say what the doc says in prose: how much we saw (count, coverage) outweighs how
    tidy it looked (streak, fit), because a beautiful line through four points out of ten periods
    is the exact object the coverage floor exists to distrust.
    """
    count_bp = min(point_count, CONFIDENT_POINTS) * 10_000 // CONFIDENT_POINTS
    streak_bp = min(streak_periods, point_count) * 10_000 // max(point_count, 1)
    fit_bp = 10_000 - min(dispersion_bp, 10_000)
    combined = (3 * count_bp + 3 * coverage_ratio_bp + 2 * streak_bp + 2 * fit_bp) // 10
    return combined * MAX_TREND_CONFIDENCE_BP // 10_000


def _refusal(series: Sequence[MetricPoint], metric: str, direction: TrendDirection,
             coverage_ratio_bp: int, point_count: int) -> Trend:
    """A refusal, carrying its receipt and nothing else.

    No confidence and no streak, which the contract enforces and which is the point: a number
    attached to an answer we declined to give is a number a ranker will sort on. The evidence
    points still travel, so a card that wants to say "we cannot see enough of this" can show
    exactly which periods it could not see.
    """
    return Trend(metric=metric, direction=direction, relative_slope_bp=0, streak_periods=0,
                 point_count=point_count, coverage_ratio_bp=coverage_ratio_bp,
                 trend_confidence_bp=0, evidence_points=tuple(series))


def compute_trend(series: Sequence[MetricPoint], *,
                  min_points: int = MIN_TREND_POINTS) -> Trend:
    """Doc 04's six ordered steps. A dense series in, one typed `Trend` out.

    PURE — no database, no network, no clock, no model. `eval_time` does not appear because
    nothing here needs one: the series already carries the periods it describes, and a function
    that read a clock would give two different answers for one stored series depending on when it
    was asked.

    `series` must be DENSE — every period in range present, gaps carried as `known=False` — which
    is exactly what `history.read_series` returns. A caller that filtered its gaps out first would
    hand this function a 100%-coverage series that is nothing of the kind, and the coverage floor
    would pass on a series it exists to refuse.

    Raises `ValueError` on an empty series rather than returning a refusal: `Trend` requires its
    evidence points, an empty series has none, and "no trend, no receipt" is a caller bug (asking
    about a period range that does not exist) rather than a fact about the tenant's data.
    """
    points = tuple(series)
    if not points:
        raise ValueError(
            "compute_trend needs a series — a trend with no evidence points is a claim with no "
            "receipt, and there is no honest direction to return for a range that holds nothing")
    if isinstance(min_points, bool) or not isinstance(min_points, int):
        raise TypeError("min_points must be an integer")
    if min_points < MIN_TREND_POINTS:
        raise ValueError(
            f"min_points cannot be lowered below {MIN_TREND_POINTS} — V-5 is a contract rule, and "
            "under four points there is no series, only two readings and a line drawn between them")

    metric = points[0].metric
    pairs = _known_pairs(points)
    point_count = len(pairs)
    coverage_ratio_bp = point_count * 10_000 // len(points)

    # STEP 1 · COVERAGE. Refuses in the doc's order: too little history is a different sentence
    # from too many holes, and reporting the second when the first is true would tell a tenant to
    # connect a source when the truth is that we have only been watching for three weeks.
    if point_count < min_points:
        return _refusal(points, metric, TrendDirection.INSUFFICIENT_HISTORY,
                        coverage_ratio_bp, point_count)
    if coverage_ratio_bp < COVERAGE_FLOOR_BP:
        return _refusal(points, metric, TrendDirection.INSUFFICIENT_COVERAGE,
                        coverage_ratio_bp, point_count)

    # STEPS 2-4 · SLOPE, NORMALISE, DIRECTION. Both slopes, both normalised against the same base.
    base = _base_value(pairs)
    ls_slope_scaled = _ls_slope_scaled(pairs)
    robust_slope_scaled = _robust_slope_scaled(pairs)
    relative_slope_bp = _clamp_bp(_idiv(robust_slope_scaled, base))
    ls_relative_bp = _clamp_bp(_idiv(ls_slope_scaled, base))
    direction = _direction(relative_slope_bp, ls_relative_bp)

    # STEPS 5-6 · STREAK and CONFIDENCE.
    streak_periods = _streak(points, direction)
    confidence_bp = _confidence_bp(
        point_count=point_count, coverage_ratio_bp=coverage_ratio_bp,
        streak_periods=streak_periods,
        dispersion_bp=_dispersion_bp(pairs, ls_slope_scaled, base))
    return Trend(metric=metric, direction=direction,
                 # FLAT reports the measured drift; only a DIRECTIONAL trend is allowed to keep a
                 # signed slope the card will read as a claim, and the contract refuses the two
                 # mismatched combinations outright.
                 relative_slope_bp=relative_slope_bp, streak_periods=streak_periods,
                 point_count=point_count, coverage_ratio_bp=coverage_ratio_bp,
                 trend_confidence_bp=confidence_bp, evidence_points=points)


# =================================================================================================
# U2 · CHANGEPOINT DETECTION — "since March", not "declining"
# =================================================================================================

@dataclass(frozen=True)
class Changepoint:
    """The period a series changed direction, with both sides' trends as the receipt.

    `at` is a PERIOD boundary taken from the series itself, never a computed date: it is the
    `observed_at` of the first point of the later segment, so "since March" names a month that
    actually holds a reading. A changepoint whose period is a gap is not returned at all — see
    `find_changepoint`.
    """

    index: int
    at: datetime
    before: Trend
    after: Trend

    @property
    def turned(self) -> str:
        """The transition as a single readable token, e.g. `rising->declining`."""
        return f"{self.before.direction.value}->{self.after.direction.value}"


def find_changepoint(series: Sequence[MetricPoint], *,
                     min_points: int = MIN_TREND_POINTS) -> Changepoint | None:
    """Doc 04 U2 — the LONGEST suffix whose direction differs from the prefix's.

    Longest, so the split is scanned from the earliest legal index upward and the first qualifying
    one wins. That is what makes the answer *"since March"* rather than *"since last month"*: a
    decline that began in March also differs from the prefix when measured from June, and
    returning June would date the change to the last period the arithmetic still noticed it.

    Both segments are held to `min_points` and both must produce a real direction — a segment that
    returns `INSUFFICIENT_HISTORY` or `INSUFFICIENT_COVERAGE` cannot be one side of a claim that
    something changed, because we do not know what it was before. And the split period itself must
    be KNOWN: dating a change to a month we have no reading for is the gap-as-observation fault
    wearing a calendar.

    Returns `None` when nothing qualifies, which is the ordinary case and not a failure.
    """
    points = tuple(series)
    for split in range(min_points, len(points) - min_points + 1):
        if not points[split].known:
            continue
        before = compute_trend(points[:split], min_points=min_points)
        if before.direction in NON_ANSWERS:
            continue
        after = compute_trend(points[split:], min_points=min_points)
        if after.direction in NON_ANSWERS or after.direction is before.direction:
            continue
        return Changepoint(index=split, at=points[split].observed_at, before=before, after=after)
    return None


# =================================================================================================
# U3 · THE TREND AS A GRAPH FACT — the wiring, and the reason the other two units are reachable
# =================================================================================================

def trend_fact_field(metric: str) -> str:
    """`derived.trend.<metric>` — the `graph_facts.field` a trend is written under.

    One field per metric rather than one `derived.trend` blob per node: L3's readers select on
    `field`, and a blob would make "is engagement declining" a read of every trend the node has.
    """
    return f"{TREND_FACT_PREFIX}{require_identifier(metric, 'metric')}"


def trend_fact_value(trend: Trend, changepoint: Changepoint | None = None) -> dict[str, Any]:
    """The JSON body of the fact: the answer, its strength, and the pointer back to the series.

    The pointer is `(subject_node_id, metric, first_period, last_period)` — `metric_history`'s
    primary key minus the ambient tenant — so "where did this decline come from" is a query a
    reader can actually run, rather than a claim that bottoms out in a card. The evidence VALUES
    are deliberately not copied in: they are already rows in a table built to be read across time,
    and a second copy in `graph_facts` is a second thing to keep in step with retention.
    """
    body: dict[str, Any] = {
        "metric": trend.metric,
        "direction": trend.direction.value,
        "relative_slope_bp": trend.relative_slope_bp,
        "streak_periods": trend.streak_periods,
        "point_count": trend.point_count,
        "coverage_ratio_bp": trend.coverage_ratio_bp,
        "trend_confidence_bp": trend.trend_confidence_bp,
        "series": {
            "subject_node_id": trend.evidence_points[0].subject_node_id,
            "metric": trend.metric,
            "unit": trend.evidence_points[0].unit.value,
            "first_period": trend.evidence_points[0].observed_at.isoformat(),
            "last_period": trend.evidence_points[-1].observed_at.isoformat(),
            "periods": len(trend.evidence_points),
        },
    }
    if changepoint is not None:
        body["changepoint"] = {"at": changepoint.at.isoformat(), "turned": changepoint.turned}
    return body


def _window_start(eval_time: datetime, grain: MetricGrain, periods: int) -> datetime:
    """The boundary `periods - 1` periods before `eval_time`'s period. No calendar library.

    Walks backwards through `period_start` for months so the month arithmetic is the store's own
    and a 31st never lands on a phantom boundary; weeks are seven days, exactly as
    `history.next_period` adds them.
    """
    start = period_start(eval_time, grain)
    if grain is MetricGrain.WEEK:
        return start - timedelta(days=7 * (periods - 1))
    year, month = divmod(start.year * 12 + (start.month - 1) - (periods - 1), 12)
    return start.replace(year=year, month=month + 1, day=1)


def _trended_pairs(store, org_id: str, limit: int) -> list[tuple[str, str]]:
    """Every `(node, metric)` this org has history for, ordered, capped.

    Read off `metric_history` rather than off the node table: the sampler's policy has already
    decided which nodes and metrics are worth a series, and re-deriving that decision here would
    be a second copy of BLG-07 that can disagree with the first. A pair with no points cannot
    produce a trend anyway.
    """
    from sqlalchemy import text

    from genios_engine.context.analytic.history import HISTORY_TABLE

    with store.engine.connect() as conn:
        rows = conn.execute(text(
            f"select distinct subject_node_id, metric from {HISTORY_TABLE} where org_id = :o "
            "order by subject_node_id, metric limit :n"), {"o": org_id, "n": limit}).all()
    return [(row[0], row[1]) for row in rows]


def _write_trend_fact(conn, *, org_id: str, node_id: str, field_name: str, value: dict[str, Any],
                      now: datetime) -> None:
    """The version-keyed upsert every derived writer in L2 uses, and THE BOUNDING PROPERTY of U3.

    `graph_facts` is keyed on `fact_version_id`, so a recompute OVERWRITES its own row rather than
    appending one per sweep. That is not a detail here: `expertise_packages` reached 181 MB across
    345 rows and put this database into read-only, and the shape that did it was a lifecycle
    transition appending a row every time it ran. A trend is recomputed on every drain, so an
    appending writer would add one row per node per metric per sweep forever — which on an org
    with 5000 nodes and twelve metrics is 60000 rows a sweep. The deterministic version id makes a
    sweep that runs twice in one period write the same row twice, and hold the table at exactly
    one row per (node, metric) for the life of the tenant.

    No new table, so nothing is added to `api/account_routes._ORG_SCOPED_TABLES` — `graph_facts` is
    already on it, and these rows are erased with the tenant by the entry that is already there.
    """
    from sqlalchemy import text

    conn.execute(text(
        "insert into graph_facts (fact_version_id, fact_id, org_id, subject_node_id, "
        "field, value, value_type, status, authority_rank, confidence, occurred_at, "
        "valid_from, visibility_scope) values "
        "(:vid, :fid, :o, :n, :f, cast(:v as jsonb), :vt, 'active', 100, 0.9, :now, :now, 'org') "
        "on conflict (fact_version_id) do update set value = excluded.value, "
        "occurred_at = excluded.occurred_at, valid_from = excluded.valid_from"),
        {"vid": f"fv_trend_{node_id}_{field_name}", "fid": f"f_trend_{node_id}_{field_name}",
         "o": org_id, "n": node_id, "f": field_name,
         "v": json.dumps(value, default=str, sort_keys=True), "vt": TREND_VALUE_TYPE, "now": now})


def refresh_trend_facts(store, org_id: str, *, eval_time: datetime,
                        history: Any = None, registry: MetricRegistry | None = None,
                        window_periods: int = TREND_WINDOW_PERIODS,
                        limit: int = MAX_TREND_FACTS_PER_SWEEP) -> int:
    """U3 — recompute every trend this org has history for and write it back. Returns rows written.

    Called from `context/runner.process_pending`, immediately after the sampler that produced the
    points. Here rather than on a schedule for the reason the whole layer prefers: the Celery
    broker is a quota-limited Upstash instance, and the drain is the only thing that knows an org
    is active.

    **REFUSALS ARE WRITTEN TOO, and that is deliberate.** The cheap-looking alternative — write
    only RISING/DECLINING/FLAT — leaves last week's `DECLINING` sitting on a node whose series has
    since gone dark, which is the stale-fact fault: a card would keep citing a decline that the
    data no longer supports and nothing would ever retract it. Writing the refusal overwrites the
    same version-keyed row with "we cannot see enough of this", so the fact self-corrects on the
    next sweep and the row count does not move.

    `eval_time` is a parameter with no default and no fallback clock. It is the `as_at` horizon of
    every read as well as the end of every window, so a trend computed for a past instant uses
    only what was known then — which is the entire reason the history store records `sampled_at`
    separately from `observed_at`.
    """
    from genios_engine.context.analytic.sampler import resolve_history_store, sampler_registry

    at = require_aware(eval_time, "eval_time")
    registry = registry or sampler_registry()
    history = history if history is not None else resolve_history_store(store)

    written = 0
    facts: list[tuple[str, str, dict[str, Any]]] = []
    for node_id, metric in _trended_pairs(store, org_id, limit):
        definition: MetricDefinition | None = registry.get(metric)
        if definition is None:
            continue          # written under a name this process does not define; not ours to read
        series = history.read_series(
            org_id, node_id, metric,
            since=_window_start(at, definition.grain, window_periods), until=at, as_at=at)
        if not series:
            continue
        trend = compute_trend(series)
        changepoint = None if trend.direction in NON_ANSWERS else find_changepoint(series)
        facts.append((node_id, trend_fact_field(metric), trend_fact_value(trend, changepoint)))

    if not facts:
        return 0
    with store.engine.begin() as conn:
        for node_id, field_name, value in facts:
            _write_trend_fact(conn, org_id=org_id, node_id=node_id, field_name=field_name,
                              value=value, now=at)
            written += 1
    return written


__all__ = ["CONFIDENT_POINTS", "COVERAGE_FLOOR_BP", "DIRECTION_THRESHOLD_BP",
           "MAX_TREND_FACTS_PER_SWEEP", "TREND_FACT_PREFIX", "TREND_VALUE_TYPE",
           "TREND_WINDOW_PERIODS", "Changepoint", "compute_trend", "find_changepoint",
           "refresh_trend_facts", "trend_fact_field", "trend_fact_value"]
