"""g-i-8 foundations: audit_log (partitioned) + intervention/calibration/resolution/roi metrics.

Revision ID: 0010_g_i_8_foundations
Revises: 0009_g_i_7_delivery
Create Date: 2026-06-02

Notes:
- audit_log uses Postgres RANGE partitioning by month. We create the parent
  table partitioned and pre-create 12 monthly partitions ahead. Operator
  script `scripts/audit_partitions.py` rolls partitions forward.
- audit_log has UPDATE/DELETE blocked via a trigger (revoke also possible via
  GRANT, but a trigger is portable and easier to test).
- All five tables are plain CREATE on SQLite (used by tests); partitioning
  + trigger only applied when the bind dialect is postgresql.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Any

import sqlalchemy as sa
from alembic import op

revision: str = "0010_g_i_8_foundations"
down_revision: str | None = "0009_g_i_7_delivery"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


PARTITION_LOOKAHEAD_MONTHS = 12


def upgrade() -> None:
    bind = op.get_bind()
    is_pg = bind.dialect.name == "postgresql"

    _create_audit_log(is_pg)
    _create_intervention_metrics()
    _create_calibration_metrics()
    _create_resolution_metrics()
    _create_roi_metrics()

    if is_pg:
        _install_audit_immutability_trigger()
        _create_initial_partitions(bind)


def downgrade() -> None:
    bind = op.get_bind()
    is_pg = bind.dialect.name == "postgresql"
    if is_pg:
        op.execute("DROP TRIGGER IF EXISTS trg_audit_log_immutable ON audit_log;")
        op.execute("DROP FUNCTION IF EXISTS audit_log_block_modify();")

    op.drop_table("roi_metrics")
    op.drop_table("resolution_metrics")
    op.drop_table("calibration_metrics")
    op.drop_table("intervention_metrics")
    op.drop_table("audit_log")


# ─────────────────────────────────────────────────────────────────────────────
# Table builders
# ─────────────────────────────────────────────────────────────────────────────


def _create_audit_log(is_pg: bool) -> None:
    if is_pg:
        op.execute(
            """
            CREATE TABLE audit_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                org_id VARCHAR(64) NOT NULL,
                actor_type VARCHAR(16) NOT NULL,
                actor_id VARCHAR(128) NOT NULL,
                action VARCHAR(64) NOT NULL,
                target_type VARCHAR(64) NOT NULL,
                target_id VARCHAR(128) NOT NULL,
                metadata_jsonb JSONB NOT NULL DEFAULT '{}'::jsonb,
                timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                PRIMARY KEY (id, timestamp)
            ) PARTITION BY RANGE (timestamp);
            """
        )
        op.execute(
            "CREATE INDEX ix_audit_org_ts ON audit_log (org_id, timestamp);"
        )
        op.execute(
            "CREATE INDEX ix_audit_org_action_ts "
            "ON audit_log (org_id, action, timestamp);"
        )
        op.execute("CREATE INDEX ix_audit_target ON audit_log (target_type, target_id);")
        return

    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer, sa.Identity(always=False), primary_key=True),
        sa.Column("org_id", sa.String(64), nullable=False),
        sa.Column("actor_type", sa.String(16), nullable=False),
        sa.Column("actor_id", sa.String(128), nullable=False),
        sa.Column("action", sa.String(64), nullable=False),
        sa.Column("target_type", sa.String(64), nullable=False),
        sa.Column("target_id", sa.String(128), nullable=False),
        sa.Column("metadata_jsonb", sa.JSON, nullable=False, server_default="{}"),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            nullable=False,
            primary_key=True,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_audit_org_ts", "audit_log", ["org_id", "timestamp"])
    op.create_index(
        "ix_audit_org_action_ts", "audit_log", ["org_id", "action", "timestamp"]
    )
    op.create_index("ix_audit_target", "audit_log", ["target_type", "target_id"])


def _create_intervention_metrics() -> None:
    op.create_table(
        "intervention_metrics",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("org_id", sa.String(64), nullable=False),
        sa.Column("module_id", sa.String(64), nullable=False),
        sa.Column("date", sa.Date, nullable=False),
        sa.Column("total_decisions", sa.Integer, nullable=False, server_default="0"),
        sa.Column("autonomous_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("notify_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("flag_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("human_overrides_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("intervention_rate", sa.Float, nullable=False, server_default="0"),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint(
            "org_id", "module_id", "date", name="uq_intervention_org_module_date"
        ),
    )
    op.create_index(
        "ix_intervention_org_date", "intervention_metrics", ["org_id", "date"]
    )


def _create_calibration_metrics() -> None:
    op.create_table(
        "calibration_metrics",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("org_id", sa.String(64), nullable=False),
        sa.Column("module_id", sa.String(64), nullable=False),
        sa.Column("window_start", sa.Date, nullable=False),
        sa.Column("window_end", sa.Date, nullable=False),
        sa.Column("predicted_bucket", sa.String(16), nullable=False),
        sa.Column("bucket_lower", sa.Float, nullable=False),
        sa.Column("bucket_upper", sa.Float, nullable=False),
        sa.Column("sample_size", sa.Integer, nullable=False, server_default="0"),
        sa.Column(
            "mean_predicted_confidence", sa.Float, nullable=False, server_default="0"
        ),
        sa.Column("actual_outcome_rate", sa.Float, nullable=False, server_default="0"),
        sa.Column("brier_score", sa.Float, nullable=False, server_default="0"),
        sa.Column("ece_contribution", sa.Float, nullable=False, server_default="0"),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index(
        "ix_calib_org_module_window",
        "calibration_metrics",
        ["org_id", "module_id", "window_start", "window_end"],
    )


def _create_resolution_metrics() -> None:
    op.create_table(
        "resolution_metrics",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("org_id", sa.String(64), nullable=False),
        sa.Column("module_id", sa.String(64), nullable=False),
        sa.Column("date", sa.Date, nullable=False),
        sa.Column("symbolic_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("neural_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("hybrid_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column(
            "symbolic_resolution_rate", sa.Float, nullable=False, server_default="0"
        ),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint(
            "org_id", "module_id", "date", name="uq_resolution_org_module_date"
        ),
    )


def _create_roi_metrics() -> None:
    op.create_table(
        "roi_metrics",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("org_id", sa.String(64), nullable=False),
        sa.Column("module_id", sa.String(64), nullable=False),
        sa.Column("date", sa.Date, nullable=False),
        sa.Column(
            "autonomous_actions_count", sa.Integer, nullable=False, server_default="0"
        ),
        sa.Column("estimated_value_usd", sa.Float, nullable=False, server_default="0"),
        sa.Column("llm_cost_usd", sa.Float, nullable=False, server_default="0"),
        sa.Column("infra_cost_usd", sa.Float, nullable=False, server_default="0"),
        sa.Column("roi_ratio", sa.Float, nullable=False, server_default="0"),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint("org_id", "module_id", "date", name="uq_roi_org_module_date"),
    )


# ─────────────────────────────────────────────────────────────────────────────
# Postgres-only: append-only trigger + monthly partitions
# ─────────────────────────────────────────────────────────────────────────────


def _install_audit_immutability_trigger() -> None:
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_log_block_modify()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only (UPDATE/DELETE blocked)';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_log_immutable
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION audit_log_block_modify();
        """
    )


def _create_initial_partitions(bind: Any) -> None:
    """Pre-create PARTITION_LOOKAHEAD_MONTHS monthly partitions from current month."""
    now = datetime.utcnow()
    year, month = now.year, now.month
    for _ in range(PARTITION_LOOKAHEAD_MONTHS):
        start = f"{year:04d}-{month:02d}-01"
        if month == 12:
            n_year, n_month = year + 1, 1
        else:
            n_year, n_month = year, month + 1
        end = f"{n_year:04d}-{n_month:02d}-01"
        part_name = f"audit_log_{year:04d}{month:02d}"
        op.execute(
            f"CREATE TABLE IF NOT EXISTS {part_name} "
            f"PARTITION OF audit_log FOR VALUES FROM ('{start}') TO ('{end}');"
        )
        year, month = n_year, n_month
